### ISSUE TITLE
Docs on connecting to Firefox are unclear

### ISSUE THREAD

**Issue by jakub-g** [RemoteDebug/remotedebug-ios-webkit-adapter#100]
Hello,

I checked this section on debugging from Firefox (since it doesn't work in Chrome). I'm on Windows.

https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#using-with-mozilla-debuggerhtml

It says

> You can have your iOS targets show up in Mozila debugger.html, by starting remotedebug_ios_webkit_adapter --port=9222 and selecting the Chrome tab.

But the picture mentions `localhost:8000`, where does it come from? should it be 9222? 

FWIW when I open `localhost:9222` in Firefox I see a JSON `{"msg":"Hello from RemoteDebug iOS WebKit Adapter"}` and that's all (not the nice UI like on screenshost)

**Comment by auchenberg** [comment]
You can read more on how you get mozilla debugger.html going here https://github.com/devtools-html/debugger.html
