### ISSUE TITLE
Unable to inspect iphone 6 after update to ios 11.4 from 10.3.3

### ISSUE THREAD

**Issue by udhaymanhas** [RemoteDebug/remotedebug-ios-webkit-adapter#101]
Followed this
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter
When IOS was at 10.3.3 it was working fine. No errors.

I updated the IOS to lastest for iphone6 i.e. 11.4.
Followed this #79 

Getting the error

```
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
```

Tried step no 5 as mentioned in #79 (comment) for iphone6.
It didn't work.

I am on windows 7 ultimate. Is this the problem?

**Comment by FarbrorGarbo** [comment]
I have also followed https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79 and debugging worked for a short period using port 9221 that seems to be default for version 1.8 of ios adapter. Then I got the same log errors as above. I'm on Windows 10.

**Comment by auchenberg** [comment]
See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79
