### ISSUE TITLE
404 not found connecting to remote target

### ISSUE THREAD

**Issue by jyn514** [RemoteDebug/remotedebug-ios-webkit-adapter#103]
When clicking on a target in chrome devtools, 404 Not Found pops up in a new window. It's detecting the iPad - I can see the title and url of the page in chrome://inspect - but it gives a 404 when I try to debug it.

The url of the 404 page is `chrome-devtools://devtools/remote/serve_file/@7d149ef5473e980f0b3babd4d0f2839cb9338e73/inspector.html?remoteFrontend=true&dockSide=undocked`.

If I open devtools in *that* window, I get the following error:
```
Uncaught TypeError: Cannot read property 'dispatchMessage' of undefined
    at DevToolsAPIImpl._dispatchOnInspectorFrontendAPI (devtools_compatibility.js:57)
    at DevToolsAPIImpl.dispatchMessage (devtools_compatibility.js:134)
    at <anonymous>:1:13
```
the relevant source from devtools_compatibility is 
```
  /**
     * @param {string} method
     * @param {!Array<*>} args
     */
    _dispatchOnInspectorFrontendAPI(method, args) {
      const inspectorFrontendAPI = /** @type {!Object<string, function()>} */ (window['InspectorFrontendAPI']);
      inspectorFrontendAPI[method].apply(inspectorFrontendAPI, args);
    }
```
Presumably `dispatchMessage` is the `method` and it's throwing an error because `window['InspectorFrontendAPI']` is undefined.

On the command line, I see the following when I click on the link in inspect:
```
New websocket connection to /ios_04bbbf5b164844759baa9eddfba6fe72ada59f95/PID:3695
Existing target found for id PID:3695
Socket is closed
Connection established to ws://localhost:9101/devtools/page/1
```

**Comment by auchenberg** [comment]
What version of Chrome and platform are you using?

**Comment by jyn514** [comment]
`Chrome: Version 67.0.3396.99 (Official Build) (64-bit)`
`iOS: 10.2.1`

I'm trying to debug an iPad. The problem is present both in standalone mode and normal safari.

**Comment by ijse** [comment]
```
ios: 12.1.3(16D40)
Chrome: Version 71.0.3578.98 (Official Build) (64-bit)
```

![image](https://user-images.githubusercontent.com/475440/51812121-25e60000-22eb-11e9-8218-ab3d61386632.png)

**Comment by hechengxixi** [comment]
I have the same issue. do you have solution?

**Comment by MySecondLife** [comment]
Got the same issue as ijse attatched.

```
OS: macOS 10.13.6
Chrome: 80.0.3987.132
Device version:  ios 12.4
```

**Comment by ErAz7** [comment]
same here

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
