### ISSUE TITLE
 can inspect Safari pages, but  can't see my hybrid app page

### ISSUE THREAD

**Issue by dream-approaching** [RemoteDebug/remotedebug-ios-webkit-adapter#104]
I follow the steps to perform remotedebug_ios_webkit_adapter --port=9000, then open safari to see the page, but open my app and it doesn't show。what caused the problem？

**Comment by auchenberg** [comment]
If your are trying to debug a production app that's using a webview, then it's not possible as Apple don't allow remote debugging connections for prod apps. See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/53
