### ISSUE TITLE
Cant see the screencasting in Chrome DevTools 

### ISSUE THREAD

**Issue by rockzill** [RemoteDebug/remotedebug-ios-webkit-adapter#105]
Hi.
I have connected my iPhone and can see only html structure and other things, but cant see screencasting from my devices.
How can I fix this?
Thanks in advance for reply, it is highly appreciated.
Regards,
Alex.
![screen shot 2018-07-13 at 12 12 35](https://user-images.githubusercontent.com/6931759/42686482-57049f94-8696-11e8-94a0-484caa071bdb.png)

**Comment by rockzill** [comment]
debug info
![screen shot 2018-07-13 at 12 37 31](https://user-images.githubusercontent.com/6931759/42687592-93823fa0-8699-11e8-8463-fb3dddc062de.png)

**Comment by auchenberg** [comment]
@rockzill Is your phone unlocked? Can you see Safari on your phone?

**Comment by rockzill** [comment]
@auchenberg Thanks for your reply. Yes, my phone is unlocked and safari is running on it.
Also I would like to mention that `remotedebug_ios_webkit_adapter --port=9000` command does not execute `os-webkit-debug-proxy` automatically. I need to run it manually before remotedebug_ios_webkit_adapter

**Comment by rockzill** [comment]
Fixed this by specifying the same port 9222 instead of 9000 for remotedebug_ios_webkit_adapter. Works now. Thank you @auchenberg  for awesome tool!

**Comment by auchenberg** [comment]
👍
