### ISSUE TITLE
Don't find devices on macOs

### ISSUE THREAD

**Issue by patrick511** [RemoteDebug/remotedebug-ios-webkit-adapter#107]
I have run 
DEBUG=remotedebug remotedebug_ios_webkit_adapter --port=9000
but there is no devices no chrome

<img width="750" alt="964d82c4-6bb0-4e9a-a0e8-d0440adc728a" src="https://user-images.githubusercontent.com/22561296/43120382-970a3522-8f4c-11e8-9f44-48e7874b8ba4.png">
<img width="570" alt="a321dbbc-3788-4a98-b0a0-cf04d2085148" src="https://user-images.githubusercontent.com/22561296/43120387-9d70dd4e-8f4c-11e8-9981-a476f5a31d6d.png">
<img width="396" alt="985e7952-4806-4d11-8859-2b3357971ebb" src="https://user-images.githubusercontent.com/22561296/43120398-a0017d84-8f4c-11e8-940d-9e6c6c1303cd.png">

I can debug it on safari

<img width="820" alt="screen shot 2018-07-24 at 2 21 50 pm" src="https://user-images.githubusercontent.com/22561296/43120537-2335bf08-8f4d-11e8-9c48-2917dc24f432.png">

**Comment by auchenberg** [comment]
What's the response if you visit `http://localhost:9000/json` when the adapter is running?

**Comment by patrick511** [comment]
show empty array [ ]

**Comment by auchenberg** [comment]
Interesting. What version if iOS are you using and what's the MacOS or Windows?

**Comment by patrick511** [comment]
MacOs High Sierra Version: 10.13.6
Chrome Version: 67.0.3396.99
Xcode Version: 9.3.1
Simulator: IphoneX

**Comment by GordanRatkovic** [comment]
I've been dealing with the exact same issue.
Same state in `chrome://inspect` as above, as well as an empty array being returned from `http://localhost:9000/json`

macOS: 10.13.6
Chrome: 68.0.3440.75
iPhone 5 with iOS 10.3.3

**Comment by droooney** [comment]
Exactly the same here

macOS High Sierra: 10.13.3
Chrome (beta): 69.0.3497.32
Xcode: 9.3
Simulator: iPad Air 2
iOS: 11.3

**Comment by madmicra** [comment]
Also getting the same empty array issue when launching `http://localhost:9000/json`. I get a message if though if just launch `http://localhost:9000`  `{"msg":"Hello from RemoteDebug iOS WebKit"}`. I can get it running with Chrome Dev Tools when running Safari on this device but not with Chrome (and I have a chrome specific issue to debug) the list is always blank and terminal repeatedly prints `iosAdapter.getTargets`.

macOS High Sierra: 10.13.6
Chrome 68.0.3440.70
iPhone 6s with iOS 11.2.5

**Comment by x1y9** [comment]
I got the same issue:

macOS: 10.11
Chrome: 69.0.3497.81
iPhone 5s with iOS 10.3.3

after I restart macOS, everything is ok.

**Comment by rohanprasad** [comment]
Hey guys, facing the same issue. Any update would be appreciated, thanks.

**Comment by auchenberg** [comment]
@rohanprasad This is an open source project where people contribute on an volunteer basis. 

Please feel free to help debug and fix this issue, if you need this fixed.

**Comment by rohanprasad** [comment]
Sure @auchenberg, from what I understand this tool makes use of https://github.com/google/ios-webkit-debug-proxy. I tried using the `ios-webkit-debug-proxy` but the result was the same. Let me know if I am correct, I'll create an issue in that repo.

**Comment by armaanahluwalia** [comment]
Same issue here

**Comment by JoakimFFCG** [comment]
I had the same issue. Got it to work by installing usbmuxd with --HEAD:

```
brew reinstall --HEAD usbmuxd
brew reinstall --HEAD libimobiledevice
brew reinstall --HEAD ios-webkit-debug-proxy
```

However, I suspect this issue can be caused by several things. I would suggest running ios-webkit-debug-proxy separately and see what error you get. I got:
```
> ios_webkit_debug_proxy --debug
[...]
Could not connect to lockdownd, error code -13. Exiting.
```

**Comment by sandcastle** [comment]
@JoakimFFCG - thanks this fixed my issues :)

**Comment by auchenberg** [comment]
Readme instructions updated in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#osxmac

**Comment by droooney** [comment]
The fix didn't help - same issue.
