### ISSUE TITLE
不支持ios chrome的调试？找不到设备

### ISSUE THREAD

**Issue by houruyaogeili** [RemoteDebug/remotedebug-ios-webkit-adapter#109]

**Comment by auchenberg** [comment]
@houruyaogeili Please open this issue in English.

**Comment by Verten** [comment]
OK, let translate in english.
"Does this tool support debug IOS chrome in MAC or windows?"

**Comment by auchenberg** [comment]
No, you can't debug Chrome on iOS, as Apple doesn't allow remote debugging of apps using the web view.
