### ISSUE TITLE
It works for safari, but not for APP's WebViews

### ISSUE THREAD

**Issue by karlflexchan** [RemoteDebug/remotedebug-ios-webkit-adapter#113]
It works for safari, but not for APP's WebViews. Inspectable pages not found any APP's WebView

**Comment by auchenberg** [comment]
@karlflexchan Is your apps running in development mode? You can't inspect production app webviews

**Comment by nikolayivanovivanov** [comment]
Does this mean that you cannot debug websites loaded in Firefox or Chrome for iOS? I guess they use WebView.

**Comment by hite** [comment]
If RemoteDebug can't inspect production app WebView , why I don't use develop tool in Safari? that is my goal to try RemoteDebug.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
