### ISSUE TITLE
Some error messages appear empty in Chrome Console

### ISSUE THREAD

**Issue by felixbohnacker** [RemoteDebug/remotedebug-ios-webkit-adapter#114]
I'm trying to debug Safari on an iPad running iOS 11.4.1 on a Windows 10 1709 laptop with Chrome 68.0.3440.106. In general, I got it to work following the instructions mentioned in this comment: https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-351472710

However, there's one issue: some error messages appear empty as shown in the attached screenshot:
![image](https://user-images.githubusercontent.com/10559462/44393721-c0b90200-a535-11e8-8035-05fd0c197b52.png) When opening the same page on my laptop, the "content" of these error messages is shown though.

Unfortunately, I haven't found anything when going through the list of open issues. I also hope that I didn't miss any setting that has to be adjusted for this to work properly...

Any input would be greatly appreciated!

**Comment by auchenberg** [comment]
Could be due to a change in Chrome DevTools, so the adaptor probably needs to get updated.

**Comment by Sikta** [comment]
I am seeing this as well. Also, I'm not able to inspect the values of any of my variables when hitting a breakpoint.. They all say "Reference not found".

**Comment by mendeel** [comment]
Having this as well! I was thinking that it was actually my installation which I had lots of trouble to get to work.

**Comment by ljupcospeci** [comment]
Having the same issue here, using Win 10 and latest iOS (v12.1.4).
