### ISSUE TITLE
 Unable to run on windows. error: adapter.spawnProcess.close, code=255

### ISSUE THREAD

**Issue by li25a** [RemoteDebug/remotedebug-ios-webkit-adapter#115]
Trying to set it up on a Windows 64 environment, using bash on ubuntu (on Windows)

Installed dependencies, as well as the x64 version with scoop. Adapter installed, and device connected successfully. Port 9000 is set to discoverable in chrome://inspect/#devices

Upon running remotedebug_ios_webkit_adapter --port=9000, I get the error message of 
`remotedebug-ios-webkit-adapter failed to run with the following error: adapter.spawnProcess.close, code=255`
`DEBUG=remotedebug remotedebug_ios_webkit_adapter` returns 
![image](https://user-images.githubusercontent.com/5191172/44488126-f9d09f80-a625-11e8-8f28-159d33f5d960.png)

**Comment by auchenberg** [comment]
Please validate that https://github.com/google/ios-webkit-debug-proxy works under WSL. Might be a new scenario that needs to be supported. Alternatively try outside of WSL.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
