### ISSUE TITLE
Can't debug website through local network

### ISSUE THREAD

**Issue by h0rn3z0r** [RemoteDebug/remotedebug-ios-webkit-adapter#116]
Debugging works flawlessly for me except when I am trying to inspect local web page, for example, http://10.0.1.x

```
New websocket connection to /ios_b668e29d662f87d0176a52c00b27fa3d8d59d409/PID:1873
Connection established to ws://localhost:9101/devtools/page/4
iosAdapter.getTargets
(node:7044) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at _target.callTarget.then (C:\Users\User\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\protocols\ios\screencast.js:24:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:7044) UnhandledPromiseRejectionWarning: #<Object>
(node:7044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:7044) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at _target.callTarget.then (C:\Users\User\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\protocols\ios\screencast.js:24:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

I have managed to access this page after different combinations of plugging/unplugging USB, turning inspector on/off, but only once. Could you please correct me if I do something wrong here?

Config:
iPad Mini 2 (iOS 9.0.2)
Windows 10
Chromium 69

**Comment by oshihirii** [comment]
I am also trying to debug localhost, eg:

    192.168.1.4:3000

I can see the site listed at:

    chrome://inspect/#devices

but when I click on `Inspect`, there is no content in dev tools `Elements` or `Console` panes, and also no URL above the `screencast` area.  

To install, i followed steps here:  

https://washamdev.com/debug-a-website-in-ios-safari-on-windows/

Windows 10
iPhone 4 (MC603X/A)  
iOS 7.1.2
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

(**Update:** Actually, localhost is working for me now, my PC had just disconnected from phone automatically and there was a permission pop up in windows that i think might have been stopping access to phone)

(**Update 2:** Performance is quite intermittent - for example now, i do not see anything listed at `chrome://inspect/#devices` so I cannot inspect anything)

**Comment by tarunChaudharyQA** [comment]
> Debugging works flawlessly for me except when I am trying to inspect local web page, for example, http://10.0.1.x
> 
> ```
> New websocket connection to /ios_b668e29d662f87d0176a52c00b27fa3d8d59d409/PID:1873
> Connection established to ws://localhost:9101/devtools/page/4
> iosAdapter.getTargets
> (node:7044) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
>     at _target.callTarget.then (C:\Users\User\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\protocols\ios\screencast.js:24:44)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:7044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
> (node:7044) UnhandledPromiseRejectionWarning: #<Object>
> (node:7044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
> (node:7044) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
>     at _target.callTarget.then (C:\Users\User\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\protocols\ios\screencast.js:24:44)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:7044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
> ```
> 
> I have managed to access this page after different combinations of plugging/unplugging USB, turning inspector on/off, but only once. Could you please correct me if I do something wrong here?
> 
> Config:
> iPad Mini 2 (iOS 9.0.2)
> Windows 10
> Chromium 69

I am also experiencing the same issue. Any Update on it?

**Comment by Nixen85** [comment]
I am also facing this issue!

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
