### ISSUE TITLE
[Windows] Release a new version to make it working accordingly to README.md

### ISSUE THREAD

**Issue by sneko** [RemoteDebug/remotedebug-ios-webkit-adapter#117]
Hi @auchenberg,

I posted (https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/52#issuecomment-299671545) a while ago how to make it working on Windows since the library `remotedebug-ios-webkit-adapter` was using a deprecated one (`vs-libimobile`). Then the documentation has been updated and easy for people to understand.

But a recent merged PR (https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/pull/111/files) has cleaned the docs since it's trying to access the `ios-webkit-debug-proxy` version installed through `scoop` Windows package manager. The main problem is people are reading README.md from the master branch on GitHub but when installing through `npm install` they get the `v0.2.2` (https://www.npmjs.com/package/remotedebug-ios-webkit-adapter?activeTab=versions) so It's not using the right `ios-webkit-debug-proxy.exe`.

Could you please release a new version?

Thank you,

**Comment by auchenberg** [comment]
New version released. https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/releases/tag/v0.3.0

**Comment by dlong500** [comment]
Looks like the latest v0.3.1 still needs to be pushed to npm?  I'm still getting the v0.3.0 release.

**Comment by auchenberg** [comment]
Done
