### ISSUE TITLE
Facebook and instagram webviews are undiscoverable

### ISSUE THREAD

**Issue by sergesemashko** [RemoteDebug/remotedebug-ios-webkit-adapter#119]
I'm having an issue using remote debug for Facebook and Instagram webviews. It works fine in other apps, e.g. Twitter. Looks like Facebook and Instagram apps are doing some heavy modifications on the webview.

Have anybody faced this or knows a workaround?

**Steps to reproduce:**
- Open any link from facebook or instagram
- Opened pages are never appeared in chrome://inspect/#devices

**Comment by dossy** [comment]
Is this because Facebook and Instagram are using iOS 8.0+ WKWebView while Twitter's still using UIWebView?

#59 related?

I'm also trying to find a way to remote debug the WebView inside Facebook and Instagram on iOS.

**Comment by sergesemashko** [comment]
@dossy , hm, interesting finding, I ended up using try/catch and displaying exception log in visual debug component on the page

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
