### ISSUE TITLE
Porting forwarding feature?

### ISSUE THREAD

**Issue by kyasbal** [RemoteDebug/remotedebug-ios-webkit-adapter#120]
Is it possible to use the port forwarding feature with this tool?
![image](https://user-images.githubusercontent.com/6434708/47723539-0f9eb880-dc98-11e8-905d-1bc6877993f9.png)

At this point, I think the port forwarding feature is not working. But, is this supported? Or just a bug or any kind of trouble?

**Comment by EmmaLouS** [comment]
While using this tool, I have been forwarding via Windows hosts file (or equivalent on your OS), or by using https://localtunnel.github.io/www/ (requires NodeJS).

Hope this helps! :)

**Comment by kevin2107** [comment]
You can use ngrok for this. https://ngrok.com/download

Download and run 

`ngrok http 8000`

or whatever port you're serving on localhost

then redirect your device browser to the forwarding address ngrok provides
 
![image](https://user-images.githubusercontent.com/12036355/49049433-f3197180-f1ac-11e8-8e87-a071d4a3e1c7.png)

**Comment by kyasbal** [comment]
I see. I had been aware of the solution using ngrok. 
Now all of my questions were cleared.
I thought this could overcome the limitation not to use the port forwarding feature on iOS. But, now I see, there is no way to use that. I will continue to use ngrok! thanks.

**Comment by michaill** [comment]
I would like to open this issue again. ngrok and localtunnel solutions are not enough. they are changing URL so if you have cors policy implemented (you should have) you can't use ngrok like solutions...
