### ISSUE TITLE
Factorize logging calls

### ISSUE THREAD

**Issue by qkdreyer** [RemoteDebug/remotedebug-ios-webkit-adapter#121]
I've noticed there is 7 `Logger.log` calls and 43 `debug` calls among the code.

I guess we could remove these lines since their logs are duplicated :
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/74158b925fa03ce800fbcda3400248328d29fdf4/src/server.ts#L155
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/74158b925fa03ce800fbcda3400248328d29fdf4/src/adapters/iosAdapter.ts#L39

And replace the other ones with `debug` calls instead

Finally, if we could have a verbose or debug CLI argument, and only print `debug` calls if this argument is set up.

I could work on this PR, what do you think ?

**Comment by qkdreyer** [comment]
To be honest, what disappoint me is the `iosAdapter.getTargets` spams.

**Comment by auchenberg** [comment]
@qkdreyer I'm open to PRs ;)
