### ISSUE TITLE
iPhone 6, 7, 8 screen is displayed incorrectly in Chrome (Windows)

### ISSUE THREAD

**Issue by SerhiiStupin** [RemoteDebug/remotedebug-ios-webkit-adapter#123]
After connecting iPhone 6, 7 or 8 (iOS 10-12) to a PC using ios-webkit-debug-proxy, the phone screen is displayed incorrectly (not completely) in Chrome. The screen of the phone is much larger than the PC screen (1920*1080). In this case, the address bar is not displayed and is not available for use.
When I connect an iPhone SE (iOS 11) or 6 Plus (iOS 10), it is displayed normally, and I can see the whole screen (+ address bar).
Is there any way to fix this problem?

Thank you.

![devtools](https://user-images.githubusercontent.com/45452395/49282078-e475d780-f496-11e8-89ac-cc36fc3bd5c6.png)
6 Plus (iOS 12)
![image](https://user-images.githubusercontent.com/45452395/49450640-1ca64e80-f7e6-11e8-97f3-ab41c1094e0c.png)

**Comment by matusbielik** [comment]
the very same issue happens when debugging on Ubuntu Linux

**Comment by lcherone** [comment]
Yep on linux, bit too massive on mine, can only just about see the burger menu icon and its about 1000x1000, and cant scroll or pan around.. though its just sugar, as long as console log works..

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
