### ISSUE TITLE
Debug proxy adapter WS does not respond when appium session is open

### ISSUE THREAD

**Issue by debugger89** [RemoteDebug/remotedebug-ios-webkit-adapter#125]
Im facing the an issue while trying to interact with the debug proxy adapter web service connectivity when there is a Appium web session up and running.

### Environment : 
Mac Os X 10.14.1
Xcode 10.1
Appium Server 1.10
IOS Simulator : IPhone 5 - 10.3.1

### Issue re-production steps

1. Start an Appium web session in the simulator. 
`
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3");
desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "10000");
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 5");
URL url = new URL("http://127.0.0.1:4723/wd/hub");
driver = new IOSDriver(url, desiredCapabilities);
`
2. Now try to use the debug proxy adapter web service for getting a screenshot. (The websocket message is sent via a 3rd party chrome extension)
Webkit adapter is up and running in port 9090. http://localhost:9090/json results in the following json.
`
[
  {
    "devtoolsFrontendUrl": "https://chrome-devtools-frontend.appspot.com/serve_file/@7d149ef5473e980f0b3babd4d0f2839cb9338e73/inspector.html?experiments=true&remoteFrontend=screencast&ws=localhost:9090/ios_SIMULATOR/ws://127.0.0.1:9191/devtools/page/2",
    "faviconUrl": "",
    "thumbnailUrl": "/thumb/https://www.google.com/search?q=ec&ie=UTF-8&oe=UTF-8&hl=en&client=safari",
    "title": "ec - Google Search",
    "url": "https://www.google.com/search?q=ec&ie=UTF-8&oe=UTF-8&hl=en&client=safari",
    "webSocketDebuggerUrl": "ws://localhost:9090/ios_SIMULATOR/ws://127.0.0.1:9191/devtools/page/2",
    "appId": "PID:48919",
    "id": "ws://127.0.0.1:9191/devtools/page/2",
    "adapterType": "_ios_SIMULATOR",
    "type": "page",
    "metadata": {
      "deviceId": "SIMULATOR",
      "deviceName": "SIMULATOR",
      "url": "127.0.0.1:9191",
      "version": "9.3.0"
    }
  }
]
`
And now use the websocket debugger url mentioned above to interact with the page.
`ws://localhost:9090/ios_SIMULATOR/ws://127.0.0.1:9191/devtools/page/2`

Im using the request message as follwing :
`
{
  "id": 1,
  "method": "Page.startScreencast",
  "params": {
    "format": "jpeg"
  }
}
`
And getting the result as :
`{"id":1,"result":{}}`

### Expected result : 

The web socket should receive another message with the screenshot base64 image string.
`
{"id":1,"result":{}}

{
  "method": "Page.screencastFrame",
  "params": {
    "data": "iVBORw0KGgoAAAANSUhEUgAAAUAAAAHMCAYAAACk4......",
    "metadata": {
      "pageScaleFactor": 2,
      "offsetTop": 0,
      "deviceWidth": 320,
      "deviceHeight": 460,
      "scrollOffsetX": 0,
      "scrollOffsetY": 0,
      "timestamp": "2019-01-01T08:14:17.433Z"
    },
    "sessionId": 1
  }
}
`

### Observations

Appium remote debugger log suggests that the message is captured by remote debugger but my websocket client never gets the message.

[RemoteDebugger] Debugger returned data for message '-17' but we were not waiting for that message! result: '{"result":{"type":"string","value":"980,1409,2"},"wasThrown":false}'; error: 'null'

If the appium session is terminated, the above message works without any issue and returns the intended result.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
