### ISSUE TITLE
libimobiledevice installation issues on  Mac OSX HighSierra

### ISSUE THREAD

**Issue by greaterking** [RemoteDebug/remotedebug-ios-webkit-adapter#126]
No really and issue but suggestion...not sure how to mark this as such

I believe it would be beneficial to have this SO thread explained a bit and provided in the readme https://stackoverflow.com/questions/52602425/libusbmuxd-version-error-during-flutter-install

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
