### ISSUE TITLE
`console.groupEnd` not behaving correctly.

### ISSUE THREAD

**Issue by ethernet8023** [RemoteDebug/remotedebug-ios-webkit-adapter#129]
To reproduce:
- inspect an `about:blank` session
- in the console, run `console.group('aGroup'); console.log('contents'); console.groupEnd(); console.log('outside group');`

Expected Output:
⏷ **aGroup**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contents
outside group

Actual Output:
⏷ **aGroup**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contents
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;outside group

This issue will cause any messages logged to the console to get caught inside a group. This is especially an issue with `console.groupCollapsed`, since all further logs will be caught in the group, since `console.groupEnd` does nothing.

**Comment by ethernet8023** [comment]
@auchenberg I'd be happy to work on this if you could point me in the right direction, grepping the codebase for "console" didn't bring much up

**Comment by auchenberg** [comment]
@arilotter Have a look at the CDP APIs which this adaptor emulates, so we have to match this output in https://chromedevtools.github.io/devtools-protocol/tot/Runtime#event-consoleAPICalled

The data from Webkit looks like http://compatibility.remotedebug.org/Console/Safari%20iOS%2010.0/events/messageAdded, so there's a bit of wrapping needed.

**Comment by ethernet8023** [comment]
When you send any `consoleAPICalled` to the CDP API, if you include a `stackTrace` with an undefined `callFrames`, Chrome doesn't accept it.

`endGroup` is failing because Webkit doesn't provide a stackTrace for `endGroup` messages, and currently we expect that it always will.
I've submitted a PR to only pass the stackTrace when Webkit sends one.

**Comment by auchenberg** [comment]
Interesting, good find. Let's go with it @arilotter
