### ISSUE TITLE
Explanation about debug on Safari iOS

### ISSUE THREAD

**Issue by lewixlabs** [RemoteDebug/remotedebug-ios-webkit-adapter#134]
Hi,
i know Chrome iOS debugging is not supported
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/95

My questions are two:

1. Chrome on iOS is a "mask", is html engine the same of Safari? Can somebody confirm this?
2. Debugging from Chrome on macOS to Safari iOS, is environment (context, useragent, etc) simulated like Chrome iOS?

I have to debug Chrome iOS (not Safari) because my enterprise customer use Chrome on his agency.

Thank you for any suggestions!
Lewix

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
