### ISSUE TITLE
Error when scoop not installed in default directory

### ISSUE THREAD

**Issue by sp00n** [RemoteDebug/remotedebug-ios-webkit-adapter#140]
I installed scoop in a different directory with these commands in a PowerShell, as per the instructions on the scoop github page (https://github.com/lukesampson/scoop):
```powershell
[environment]::setEnvironmentVariable('SCOOP','C:\Tools\scoop','User')
[environment]::setEnvironmentVariable('SCOOP_GLOBAL','C:\Tools\scoop_global','Machine')
$env:SCOOP='C:\Tools\scoop'
$env:SCOOP_GLOBAL='C:\Tools\scoop_global'
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
```

However after following the install instructions for remotedebug-ios-webkit-adapter I was greeeted with the following error message:
"_remotedebug-ios-webkit-adapter failed to run with the following error: ios_webkit_debug_proxy.exe not found. Please install 'scoop install ios-webkit-debug-proxy'_"

The reason for this is that in out/adapters/iosAdapter.js the code looks for the .exe file within the USERPROFILE path variable (line 132):
```javascript
const proxy = path.resolve(__dirname, process.env.USERPROFILE + '/scoop/apps/ios-webkit-debug-proxy/current/ios_webkit_debug_proxy.exe');
```

But since if you install scoop in a different directory with the above commands, you're also setting a custom SCOOP path variable, so it would probably make sense to check if there's such a `process.env.SCOOP` variable and then use that, and only if not default to the USERPROFILE.
E.g.
```javascript
let proxy;

if ('SCOOP' in process.env) {
    proxy = path.resolve(process.env.SCOOP + '/apps/ios-webkit-debug-proxy/current/ios_webkit_debug_proxy.exe');
}
else {
    proxy = path.resolve(__dirname, process.env.USERPROFILE + '/scoop/apps/ios-webkit-debug-proxy/current/ios_webkit_debug_proxy.exe');
}

```

Or something like this, I haven't worked with node.js yet.

**Comment by auchenberg** [comment]
Already landed in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/pull/131. 

A new release have to get published.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
