### ISSUE TITLE
Instructions don't work for windows 10 out of box

### ISSUE THREAD

**Issue by joeyhub** [RemoteDebug/remotedebug-ios-webkit-adapter#141]
The instructions here don't work for windows 10, though in general dependencies are missing:

* Where does npm come from?
* Where does remotedebug_ios_webkit_adapter come from?

After installing everything:

>iosAdapter.getTargets

> error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]

While there's a lengthy discussion on this in the issue in another ticket, there's no obvious simple solution.

It would be really nice if it gave a more meaningful error message for the above. Did it manage to find a device but couldn't read it's version (could list it but not read it)?

**Comment by patricknelson** [comment]
As a new user also on Windows 10, I was also having issues. However, I realized that my issue was actually related to a recent iOS upgrade on my iPad (see #138). My main iPad is running 12.2 but I tested this on another iPad running 12.1.4 with the exact same computer and it works, so give that a shot to see if it helps.

p.s. I think **those** errors that you're seeing are normal, see https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-351472710 on that. I was still getting those even after I got it working. But I agree, that's not very useful in this scenario at all.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
