### ISSUE TITLE
inspector doesnt open

### ISSUE THREAD

**Issue by FabioYami** [RemoteDebug/remotedebug-ios-webkit-adapter#143]
everthing goes blank and show this error on console.

error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets

![image](https://user-images.githubusercontent.com/38693351/56380011-6ae14a80-61e7-11e9-9824-bcefd63a1a15.png)

**Comment by auchenberg** [comment]
What's your device and ios version @FabioYami ?

**Comment by FabioYami** [comment]
iphone 5s
version 12.2

thanks

**Comment by auchenberg** [comment]
Duplicate of https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138 then. iOS 12.2 isn't supported yet. We need some help.
