### ISSUE TITLE
Can this be used to debug google chrome on iOS?

### ISSUE THREAD

**Issue by vvo** [RemoteDebug/remotedebug-ios-webkit-adapter#144]
Hi there, I could not find the information if this can be used to debug google chrome on iOS. When I open Safari iOS then chrome://inspect do list my phone browser (even if not working since #138 but listing works). But when opening google chrome iOS then it's not listed.

Let me know!

**Comment by auchenberg** [comment]
You can't debug iOS apps using the webview when installed from the app store. Limitation of IOS and Webkit. Sadly.
