### ISSUE TITLE
Ubuntu iosAdapter.getTargets iosAdapter.getTargets iosAdapter.getTargets

### ISSUE THREAD

**Issue by bknill** [RemoteDebug/remotedebug-ios-webkit-adapter#150]
Hi, 

I'm getting

```
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
```

Over and over again on Ubuntu 18.04. 

` ios_webkit_debug_proxy` picks up the device first time, no problems. 

I saw the Windows fix to update  ios_webkit_debug_proxy, but that doesn't seem to be relevant on Ubuntu. 

Any clues?

**Comment by Us3rNaMeD** [comment]
That's supposed to happen, it indicates thats it's polling to find connected devices.

**Comment by bknill** [comment]
Hi yes. 

But there is a device connected, running `ios_webkit_debug_proxy` connects immediately, running `remotedebug_ios_webkit_adapter --port=9000` does not connect to anything. 

I've seen the Windows[ issue](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-351472710) regarding using an out of date ios_webkit_debug_proxy, could the same thing be happening in Ubuntu?

**Comment by Us3rNaMeD** [comment]
The iOS version of the device plays a big role too. Maybe your issue is related to 138 as well?
Assuming everything is up to date you should be using proxy version 1.8.4.

**Comment by bknill** [comment]
#138
