### ISSUE TITLE
What about targeting desktop versions of Safari?

### ISSUE THREAD

**Issue by paul-go** [RemoteDebug/remotedebug-ios-webkit-adapter#152]
Is there anyway way to make this tool work with the desktop version of Safari?
My specific use-case is for a WKWebView embedded in a native macOS app.

I may be willing to put together some instructions / contribute in some way if minimal work would be involved in getting this working.

**Comment by ewanharris** [comment]
I believe if this was implemented, it would be dealt with at the ios-webkit-debug-proxy level, it looks like they have already received this request previously google/ios-webkit-debug-proxy/issues/245. Based off that I'm going to close this issue
