### ISSUE TITLE
UnhandledPromiseRejectionWarning error 

### ISSUE THREAD

**Issue by SophiaBelkin** [RemoteDebug/remotedebug-ios-webkit-adapter#158]
`New websocket connection to /ios_d68f62a7c06917a99ace6b6598c08d68b1b48953/ws://127.0.0.1:9102/devtools/page/2
Connection established to ws://127.0.0.1:9102/devtools/page/2
(node:24026) UnhandledPromiseRejectionWarning: #<Object>
(node:24026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
iosAdapter.getTargets
(node:24026) UnhandledPromiseRejectionWarning: #<Object>
(node:24026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
iosAdapter.getTargets
(node:24026) UnhandledPromiseRejectionWarning: #<Object>
(node:24026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)`

**Comment by antohapan** [comment]
Hello, I have the same problem
> PS C:\WINDOWS\system32> remotedebug_ios_webkit_adapter --port=9000
remotedebug-ios-webkit-adapter is listening on port 9000
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
New websocket connection to /ios_00008020-000D24923C91002E/ws://127.0.0.1:9101/devtools/page/1
Connection established to ws://127.0.0.1:9101/devtools/page/1
(node:5384) UnhandledPromiseRejectionWarning: #<Object>
(node:5384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5384) UnhandledPromiseRejectionWarning: #<Object>
(node:5384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by Us3rNaMeD** [comment]
Would like to refer both of you to #138

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
