### ISSUE TITLE
New maintainers: Dirk-Schnorpfeil +  Ewan Harris

### ISSUE THREAD

**Issue by auchenberg** [RemoteDebug/remotedebug-ios-webkit-adapter#165]
Hi everyone 👋

I have some good news: We have gotten two new maintainers @ewanharris and @Dirk-Schnorpfeil who have reached out want to help maintain this project.

On a forward going basis, these two lovely folks will be driving the effort forward.

A warm welcome!

🎉

/k

**Comment by auchenberg** [comment]
@ewanharris You have been added to NPM and can now publish.

**Comment by ewanharris** [comment]
Thanks for the warm welcome @auchenberg!
