### ISSUE TITLE
Nothing in console

### ISSUE THREAD

**Issue by bknill** [RemoteDebug/remotedebug-ios-webkit-adapter#166]
I'm on Ubuntu 18.4 and connecting to an iPhone iOS 12.4

I can get a connection to the Phone and see 

`[{"devtoolsFrontendUrl":"https://chrome-devtools-frontend.appspot.com/serve_file/@7d149ef5473e980f0b3babd4d0f2839cb9338e73/inspector.html?experiments=true&remoteFrontend=screencast&ws=localhost:9000/ios_59ea186acd89057812aa7d0c7ec3038c596d3779/ws://127.0.0.1:9101/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/https://192.168.0.7:3000/course/lPvwP4rz","title":"ShowHow - Immersive Learning Experiences","url":"https://192.168.0.7:3000/course/lPvwP4rz","webSocketDebuggerUrl":"ws://localhost:9000/ios_59ea186acd89057812aa7d0c7ec3038c596d3779/ws://127.0.0.1:9101/devtools/page/1","appId":"PID:364","id":"ws://127.0.0.1:9101/devtools/page/1","adapterType":"_ios_59ea186acd89057812aa7d0c7ec3038c596d3779","type":"page","metadata":{"deviceId":"59ea186acd89057812aa7d0c7ec3038c596d3779","deviceName":"Trilby’s iPhone","deviceOSVersion":"12.4.0","url":"127.0.0.1:9101","version":"12.4"}},{"devtoolsFrontendUrl":"https://chrome-devtools-frontend.appspot.com/serve_file/@7d149ef5473e980f0b3babd4d0f2839cb9338e73/inspector.html?experiments=true&remoteFrontend=screencast&ws=localhost:9000/ios_59ea186acd89057812aa7d0c7ec3038c596d3779/ws://127.0.0.1:9101/devtools/page/2","faviconUrl":"","thumbnailUrl":"/thumb/https://192.168.0.7:3000/","title":"ServiceWorker","url":"https://192.168.0.7:3000/","webSocketDebuggerUrl":"ws://localhost:9000/ios_59ea186acd89057812aa7d0c7ec3038c596d3779/ws://127.0.0.1:9101/devtools/page/2","appId":"PID:413","id":"ws://127.0.0.1:9101/devtools/page/2","adapterType":"_ios_59ea186acd89057812aa7d0c7ec3038c596d3779","type":"page","metadata":{"deviceId":"59ea186acd89057812aa7d0c7ec3038c596d3779","deviceName":"Trilby’s iPhone","deviceOSVersion":"12.4.0","url":"127.0.0.1:9101","version":"12.4"}}]`

When I browse to http://127.0.0.1:9000/json

I can see the pages in Remote in Console, there is just nothing in the Dev Tools. It's completely blank. 

Any idea how to debug this or get the data?

**Comment by ewanharris** [comment]
Hey @bknill,

Did you configure dev tools to pick up targets as mentioned in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/164#issuecomment-523196609?

**Comment by bknill** [comment]
Thanks @ewanharris  Yes I did that.  I can see the pages, they're just empty.

**Comment by goleary** [comment]
I'm having the same issue on windows 10 with iOS 12.4 where I see the pages but no content when I inspect them:
![image](https://user-images.githubusercontent.com/16123225/63887814-7b25e500-c992-11e9-9333-9b7c11108049.png)
![image](https://user-images.githubusercontent.com/16123225/63887853-8a0c9780-c992-11e9-92b2-de23d98c6634.png)

**Comment by rubenlg** [comment]
Probably this:
https://github.com/google/ios-webkit-debug-proxy/issues/323

**Comment by moazam1** [comment]
Same issue on windows 10. I am seeing nothing in safari. Updated ios but no luck.

**Comment by klanglie** [comment]
Same here. This does not work on Windows 10

**Comment by goleary** [comment]
just tried it with ios 12.2 and got the same error

**Comment by D00mch** [comment]
same thing, tried with linux manjaro and windows 10.
IOS 12.4.1

**Comment by bayerlse** [comment]
Same here, are there any updates?

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
