### ISSUE TITLE
Device not getting listed in Chrome Dev Tools in MacOS 10.14.6

### ISSUE THREAD

**Issue by sethurv** [RemoteDebug/remotedebug-ios-webkit-adapter#167]
Device not getting listed in Chrome Dev Tools Remote Target with MacOS 10.14.6

Attached the debug logs 

    ~ $ DEBUG=remotedebug remotedebug_ios_webkit_adapter
      remotedebug server.run, port=9000 +0ms
      remotedebug server.setupHttpHandlers +12ms
      remotedebug iOSAdapter.getProxySettings +5ms
      remotedebug iOSAdapter.getProxyPath +0ms
      remotedebug adapterCollection.start Map {} +5ms
      remotedebug adapter.start { port: 9100,
      proxyExePath: '/usr/local/bin/ios_webkit_debug_proxy',
      proxyExeArgs: [ '--no-frontend', '--config=null:9100,:9101-9201' ],
      pollingInterval: 3000,
      baseUrl: 'http://127.0.0.1',
      path: '/json' } +1ms
      remotedebug adapter.spawnProcess, path=/usr/local/bin/ios_webkit_debug_proxy +3ms
      remotedebug server.startTargetFetcher +214ms
    remotedebug-ios-webkit-adapter is listening on port 9000
      remotedebug iOSAdapter.getTargets +5s
    iosAdapter.getTargets
      remotedebug iOSAdapter.getDeviceVersion +36ms
      remotedebug iOSAdapter.getDeviceInfoPath +1ms
      remotedebug adapter.start { port: 9101,
      pollingInterval: 3000,
      baseUrl: 'http://127.0.0.1',
      path: '/json' } +136ms
      remotedebug adapter.start: Skip spawnProcess, no proxyExePath available +1ms
      remotedebug adapter.getTargets, metadata=[object Object] +0ms
      remotedebug server.startTargetFetcher.fetched.0 +5ms
      remotedebug iOSAdapter.getTargets +5s
    iosAdapter.getTargets
      remotedebug iOSAdapter.getDeviceVersion +7ms
      remotedebug iOSAdapter.getDeviceInfoPath +1ms
      remotedebug adapter.getTargets, metadata=[object Object] +107ms
      remotedebug server.startTargetFetcher.fetched.0 +3ms
      remotedebug iOSAdapter.getTargets +5s
    iosAdapter.getTargets
      remotedebug iOSAdapter.getDeviceVersion +9ms
      remotedebug iOSAdapter.getDeviceInfoPath +1ms
      remotedebug adapter.getTargets, metadata=[object Object] +103ms
      remotedebug server.startTargetFetcher.fetched.0 +3ms
      remotedebug iOSAdapter.getTargets +5s
    iosAdapter.getTargets
      remotedebug iOSAdapter.getDeviceVersion +6ms
      remotedebug iOSAdapter.getDeviceInfoPath +0ms
      remotedebug adapter.getTargets, metadata=[object Object] +144ms
      remotedebug server.startTargetFetcher.fetched.0 +3ms

    ~ $ ios_webkit_debug_proxy
    Listing devices on :9221
    Connected :9222 to iPhone (xxx)

**Comment by sethurv** [comment]
iOS version is 12.2

I hope the issue is related to https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138

**Comment by meydominic** [comment]
Same here.
macOS 10.14.6 with iOS 12.4 emulator:
```
  remotedebug server.run, port=9000 +0ms
  remotedebug server.setupHttpHandlers +5ms
  remotedebug iOSAdapter.getProxySettings +3ms
  remotedebug iOSAdapter.getProxyPath +1ms
  remotedebug adapterCollection.start Map {} +13ms
  remotedebug adapter.start { port: 9100,
  proxyExePath: '/usr/local/bin/ios_webkit_debug_proxy',
  proxyExeArgs: [ '--no-frontend', '--config=null:9100,:9101-9201' ],
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +1ms
  remotedebug adapter.spawnProcess, path=/usr/local/bin/ios_webkit_debug_proxy +1ms
  remotedebug server.startTargetFetcher +210ms
remotedebug-ios-webkit-adapter is listening on port 9000
  remotedebug server.http.endpoint/json/version +762ms
  remotedebug server.http.endpoint/json +7ms
  remotedebug iOSAdapter.getTargets +1ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +2ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +2ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +2ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getTargets +199ms
iosAdapter.getTargets
  remotedebug server.startTargetFetcher.fetched.0 +2ms
  remotedebug server.http.endpoint/json/version +802ms
  remotedebug server.http.endpoint/json +2ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +2ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +2ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
```

![image](https://user-images.githubusercontent.com/2743382/64691513-1b9bff00-d493-11e9-8328-e9b9df844765.png)

Safari Developer Tools finds and can connect to the device without a problem.

**Comment by bmitchinson** [comment]
+1, also #141

**Comment by rulrok** [comment]
Hello, I sporadically used mac and seeing this issue popped a question in my head:

(genuine question) 
If you are already on mac, isn't it easier to use safari's remote debug directly?

Or is it because you'd rather prefer to use chrome itself instead of safari debugger?

Thanks

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
