### ISSUE TITLE
What flavor and version of Chrome should be used when using Linux to remote debug?

### ISSUE THREAD

**Issue by avnermosh** [RemoteDebug/remotedebug-ios-webkit-adapter#169]
The instructions mention to use Chrome Canary. But there is no Chrome Canary for Linux (see here: https://askubuntu.com/questions/309813/how-to-have-google-chrome-canary-on-ubuntu).
What flavor and version of Chrome should be used when using Linux to remote debug?
Thanks

**Comment by avnermosh** [comment]
I was able to use Chrome stable (not Canary) (chrome version 87.0.4280.141 (Official Build) (64-bit))
Tis is with ubuntu 20.04. See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/170#issuecomment-759926427

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
