### ISSUE TITLE
Chrome Canary is not available for Linux to remote debug

### ISSUE THREAD

**Issue by avnermosh** [RemoteDebug/remotedebug-ios-webkit-adapter#170]
The instructions mention to use Chrome Canary. 

> Usage with Chrome (Canary) and Chrome DevTools

But there is no Chrome Canary for Linux (see [here](https://askubuntu.com/questions/309813/how-to-have-google-chrome-canary-on-ubuntu))
What flavor and version of Chrome should be used when using Linux to remote debug?
Thanks

**Comment by avnermosh** [comment]
I recently repeated the steps using Ubuntu 20.04
I found that I can successfully debug a webapp that runs in Safari on iOS device using 
chrome stable (not Canary)  (chrome version 87.0.4280.141 (Official Build) (64-bit))
But the experience is somewhat limited. For example:
- I don't see the console messages
- I cannot place a breakpoint for event listener like e.g. in Chrome

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
