### ISSUE TITLE
Unable to run on Linux Ubuntu 18.04. error: adapter.spawnProcess.close, code=255

### ISSUE THREAD

**Issue by avnermosh** [RemoteDebug/remotedebug-ios-webkit-adapter#171]
```
remotedebug_ios_webkit_adapter --port=9000
remotedebug-ios-webkit-adapter failed to run with the following error: adapter.spawnProcess.close, code=255

```
----------

```
remotedebug_ios_webkit_adapter --version
0.3.2

which remotedebug_ios_webkit_adapter 
/usr/local/bin/remotedebug_ios_webkit_adapter


which ios_webkit_debug_proxy  
/usr/local/bin/ios_webkit_debug_proxy

ios_webkit_debug_proxy --version
ios_webkit_debug_proxy 1.8.5
Built with libimobiledevice v1.2.1, libplist v2.0.0

dpkg --list | grep libplist
ii  libplist++-dev                                              2.0.0-2ubuntu1                                  amd64        Library for handling Apple binary and XML property lists
ii  libplist++3v5:amd64                                         2.0.0-2ubuntu1                                  amd64        Library for handling Apple binary and XML property lists
ii  libplist-dev                                                2.0.0-2ubuntu1                                  amd64        Library for handling Apple binary and XML property lists
ii  libplist3:amd64                                             2.0.0-2ubuntu1                                  amd64        Library for handling Apple binary and XML property lists

# installed packages
dpkg --list | grep libimobiledevice|libusbmuxd 
ii  libimobiledevice-dev                                        1.2.1~git20171128.5a854327+dfsg-0.1             amd64        Library for communicating with iPhone and iPod Touch devices
ii  libimobiledevice-utils                                      1.2.1~git20171128.5a854327+dfsg-0.1             amd64        Library for communicating with iPhone and iPod Touch devices
ii  libimobiledevice6:amd64                                     1.2.1~git20171128.5a854327+dfsg-0.1             amd64        Library for communicating with the iPhone and iPod Touch
ii  libusbmuxd-dev:amd64                                        1.1.0~git20171206.c724e70f-0.1                  amd64        USB multiplexor daemon for iPhone and iPod Touch devices - devel
ii  libusbmuxd4:amd64                                           1.1.0~git20171206.c724e70f-0.1                  amd64        USB multiplexor daemon for iPhone and iPod Touch devices - library
```

**Comment by mtjn** [comment]
Do you have an iOS device plugged in, with the Trust modal confirmed, before running this command?

**Comment by uragun91** [comment]
I was able to solve this issue by just plugging in my iphone

**Comment by Fr33maan** [comment]
ios pluged in with trust enabled, computer restarted, still unable to start. 
I'm able to see my device and access to the files but not to start the server.
Yesterday it was perfectly working, I was able to use the debuger.

EDIT: use `sudo usbmuxd`

**Comment by Fr33maan** [comment]
The issue was coming from `usbmuxd` which was unable to start without sudo mode. I will have to dig to find how to run it in daemonized mode now

**Comment by CodeWithOz** [comment]
@Fr33maan did you ever figure out the problem?

**Comment by Fr33maan** [comment]
@CodeWithOz never tried to solve the issue. I simply run it with sudo in another terminal before running the debugger with `sudo usbmuxd`

I thenk the easiest solution would be to create a service run by root but as I find all this processes pretty buggy, the terminal is the good too to be able to easily kill them and restart.

**Comment by aril-spetalen** [comment]
This was helpful for me a tired morning; giving me a hint, I was trying to start the debugger without having connected the USB cable. :-D

**Comment by Fr33maan** [comment]
@aril-spetalen kind of hardware bug ? :D

**Comment by Christopher-Hayes** [comment]
For anyone who comes across this thread and is still having issues, I had to do `sudo ldconfig` instead per this thread: https://github.com/libimobiledevice/libimobiledevice/issues/183

**Comment by avnermosh** [comment]
I was able to build from source and install the following packages: libmobiledevice, libusbmuxd, usbmuxd, libplist, 
based on:
https://github.com/libimobiledevice/libimobiledevice/issues/1067#issuecomment-726234592
This is on ubuntu 20.04

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
