### ISSUE TITLE
Cannot load localhost page on iOS device over port forwarding

### ISSUE THREAD

**Issue by mtjn** [RemoteDebug/remotedebug-ios-webkit-adapter#172]
remotedebug-ios-webkit-adapter version: 0.3.2
Host OS: Ubuntu 19.0.4
Host browser: Chromium 77.0.3865.90 snap
iPhone version: 12.1

Port forwarding is definitely enabled. Localhost page is confirmed as working and accessibled on host. Device and tabs show as connected and inspectable on chrome://inspect. But Safari cannot find localhost page.

http://localhost:9000/json output:

```json
[
  {
    "devtoolsFrontendUrl": "https://chrome-devtools-frontend.appspot.com/serve_file/@7d149ef5473e980f0b3babd4d0f2839cb9338e73/inspector.html?experiments=true&remoteFrontend=screencast&ws=localhost:9000/ios_c72a798104ef8f8a2b57e7200938c41d46de9884/ws://127.0.0.1:9101/devtools/page/1",
    "faviconUrl": "",
    "thumbnailUrl": "/thumb/data:text/html,",
    "title": "Cannot Open Page",
    "url": "data:text/html,",
    "webSocketDebuggerUrl": "ws://localhost:9000/ios_c72a798104ef8f8a2b57e7200938c41d46de9884/ws://127.0.0.1:9101/devtools/page/1",
    "appId": "PID:276",
    "id": "ws://127.0.0.1:9101/devtools/page/1",
    "adapterType": "_ios_c72a798104ef8f8a2b57e7200938c41d46de9884",
    "type": "page",
    "metadata": {
      "deviceId": "c72a798104ef8f8a2b57e7200938c41d46de9884",
      "deviceName": "iPhone",
      "deviceOSVersion": "12.1.0",
      "url": "127.0.0.1:9101",
      "version": "12.1"
    }
  }
]
```

**Comment by miki995** [comment]
@mtjn That is the problem for IOS or Android itself, I suggest asking somewhere else on the internet.
Btw: I'm looking for same but no luck so far.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
