### ISSUE TITLE
Support for iOS 13

### ISSUE THREAD

**Issue by akc-kyiv** [RemoteDebug/remotedebug-ios-webkit-adapter#174]
Before iOS 13 I was able to use it following [these](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138#issuecomment-523664256) instructions.

On iOS 13 (13.1.2) the situation looks like on the screenshot:
![image](https://user-images.githubusercontent.com/25297130/66634939-d3e5d000-ec16-11e9-87d6-75e30ad3649e.png)

The same issue found [here](https://github.com/google/ios-webkit-debug-proxy/issues/314#issuecomment-501253834). Seems fixed by adding support for ssl connection.

**Comment by ewanharris** [comment]
@akc-kyiv, did you reinstall ios-webkit-debug-proxy to get the latest changes from google/ios-webkit-debug-proxy/pull/329, you'll have to use `brew install --HEAD ios-webkit-debug-proxy` to get it from the master branch as the change hasn't been put on brew yet.

I haven't had time to test that change with this project yet so I'm not 100% sure whether there's any issues

**Comment by JoeMeeks** [comment]
@ewanharris do you know of a way to do so on a PC with scoop?

Running `scoop install ios-webkit-debug-proxy@master` errors:
```
WARN  Given version (master) does not match manifest (1.8.5)
WARN  Attempting to generate manifest for 'ios-webkit-debug-proxy' (master)
Autoupdating ios-webkit-debug-proxy
Downloading ios-webkit-debug-proxy-master-win64-bin.zip to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://github.com/google/ios-webkit-debug-proxy/releases/download/vmaster/ios-webkit-debug-proxy-master-win64-bin.zip is not valid
Could not find hash!
Could not install ios-webkit-debug-proxy@master
```
Which may be because as @artygus stated, Windows binaries have not yet been built.
https://github.com/google/ios-webkit-debug-proxy/issues/314#issuecomment-539979945

**Comment by WebVooruit** [comment]
On the [homepage](https://github.com/google/ios-webkit-debug-proxy/#inspectable-pages-list-is-empty-for-ios--122) they use master of usbmuxd

**Comment by ewanharris** [comment]
@JoeMeeks, sorry I'm not familiar with scoop so I'm not sure whether that's possible. I _think_ scoop requires a release tagged on GitHub (whereas brew will build directly from the repo) so I don't think it's possible

**Comment by JoeMeeks** [comment]
@ewanharris thanks for the reply. That seems to be the case with scoop based on the common-to-other-package-manager version params I tried and no documentation that I could find otherwise.

**Comment by gilangaramadan** [comment]
@akc-kyiv hi! also experienced that, after I look again on the doc I missed installing this `brew install --HEAD usbmuxd` after that it show the device.

**Comment by imadarif** [comment]
follow this 
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/181#issuecomment-652268303

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
