### ISSUE TITLE
unable to inspect as device page is not displaying in dev tool on clicking inspect

### ISSUE THREAD

**Issue by siddhantraut** [RemoteDebug/remotedebug-ios-webkit-adapter#180]
I am not getting app webview/ webpage opened in safari browser to inspect.

<img width="1636" alt="Screen Shot 2020-01-10 at 4 43 20 PM" src="https://user-images.githubusercontent.com/21220390/72189126-0f389c00-33ca-11ea-964d-070123bce963.png">

**Comment by Zyles** [comment]
Same problem.

All I get is:
```
{
msg: "Hello from RemoteDebug iOS WebKit Adapter"
}

```
When I visit `localhost:9000` in my browser.

No page is visible.

Windows 10
ios 13,3
Iphone 11

**Comment by nar10z** [comment]
Yes, i'm have same problem
ios 12.4.4
iphone 6

**Comment by awkwarden** [comment]
same issue on Mac.
Mojave 10.14.6
ios 13.3
iPhone 11 Pro

**Comment by awkwarden** [comment]
Believe this might be a duplicate issue from #138 . Should be fixed now by installing via `npm i -g remotedebug-ios-webkit-adapter@next`

**Comment by limonfresh** [comment]
> Believe this might be a duplicate issue from #138 . Should be fixed now by installing via `npm i -g remotedebug-ios-webkit-adapter@next`

this solution works for me perfectly, thanks @awkwarden 
– MacOS Catalina 10.15.1
– iPad Air 2 with iPadOS 13.3

**Comment by jonsadka** [comment]
That solution did not work for me, as I still see no remote targets being displayed when I open Chrome on iOS. I made sure to uninstall all the dependencies and reinstall them one by one, still no success
– MacOS Catalina 10.15.2
– iPhone x with iOS 13.3.1

Navigating to the server at `localhost:9000` response with `{"msg":"Hello from RemoteDebug iOS WebKit Adapter"}`

**Comment by limonfresh** [comment]
> when I open Chrome on iOS. 

I guess this where you have mistaken. You need to open Chrome on your Mac but use the Safari on the remote device, not Chrome.

**Comment by liesauer** [comment]
Did not work for me too. already tried different ipads with different ios verisons.

**Comment by Ronsku** [comment]
+1 same issue here

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
