### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by jacobweber** [RemoteDebug/remotedebug-ios-webkit-adapter#185]
I've been tearing my hair out trying to get Safari for Mac to inspect my Cordova iOS app. Half of the time, the iOS device doesn't show up at all in Safari's Develop menu. The other half, the Inspector will open for about a second, then close with no explanation.

It took a bit of trial and error to get this adapter set up; I had to install an old version of Chromium to deal with #183, and had to install remotedebug-ios-webkit-adapter@next to deal with some other errors.

But I think I finally have a reliable way to debug Cordova iOS apps. Thank you so much! (Although it's a sad state of affairs that this is necessary, since Apple cares so little about fixing their developer tools.)

**Comment by auchenberg** [comment]
Thank you @jacobweber! Means a lot! https://mobile.twitter.com/auchenberg/status/1231805900077203456
