### ISSUE TITLE
Erase device in Android Studio

### ISSUE THREAD

**Issue by damien-nd** [RemoteDebug/remotedebug-ios-webkit-adapter#187]
I just follow the read me for MacOs and now no device are available in Android studio.
I was working fine before and few minutes before all brew and npm install.
Now after restarting Android Studio several times, I can use physical device via USB in Android Studio.

Any ideas to solve it?

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
