### ISSUE TITLE
Installation without scoop

### ISSUE THREAD

**Issue by unitrix0** [RemoteDebug/remotedebug-ios-webkit-adapter#190]
Is there a way to install this and the proxy without scoop? why?

1. I don't want to have another package thingy on my computer
2. scoop installs it into the user profile which is utter nonsense. Software doesn't belong there.

thanks

**Comment by auchenberg** [comment]
This project doesnt use scoop, but it's main dependency `ios-webkit-debug-proxy` does. Please see https://github.com/google/ios-webkit-debug-proxy#installation and open the issue there. I'm sure you can download the windows binaries somewhere outside of scoop
