### ISSUE TITLE
Error handling message from target.

### ISSUE THREAD

**Issue by keean** [RemoteDebug/remotedebug-ios-webkit-adapter#193]
When using the chrome debugger from VSCode on a macbook connecting to an iOS9 iPad, over 50% of the console log lines are:

"Error handling message from target: Message cannot be null, empty or undefined"

VSCode does not appear to be able to filter this message out. Is it possible to filter out this message in remotedebug-ios-webkit-adapter, or prevent it being generated in the first place?

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
