### ISSUE TITLE
Can't add breakpoint in macos?

### ISSUE THREAD

**Issue by reuwi** [RemoteDebug/remotedebug-ios-webkit-adapter#195]
![image](https://user-images.githubusercontent.com/23435469/82417336-ff367480-9aad-11ea-9821-cd3c1e2a4a8c.png)

I tried to add breakpoints via click the left line number in macos, but it did no work. so is it not supported yet to add  add breakpoints in debugger panel in macos?The above screenshot was the normal situation

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
