### ISSUE TITLE
iOS 13.4.1 + Windows + Listening 9000 = Nothing

### ISSUE THREAD

**Issue by raygig** [RemoteDebug/remotedebug-ios-webkit-adapter#196]
iOS: 13.4.1
Windows: 10.0.18383 Build 18363
remotedebug-ios-webkit-adapter: https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/tree/master
ios-webkit-debug-proxy: 1.8.6
iOS Safari Settings: "Web Inspector" is enabled

```
λ npm run start

> remotedebug-ios-webkit-adapter@0.4.2 start C:\Projects\remotedebug-ios-webkit-adapter
> gulp build && node out/index.js

[06:28:07] Using gulpfile C:\Projects\remotedebug-ios-webkit-adapter\gulpfile.js
[06:28:07] Starting 'build'...
[06:28:10] Finished 'build' after 2.31 s
remotedebug-ios-webkit-adapter is listening on port 9000
```

![image](https://user-images.githubusercontent.com/1569098/82805419-fd740480-9e51-11ea-9f2e-3903b495bfa9.png)

This used to work with iOS 12 and ever since iOS 13 i have never been able to get my device to show up. I have tried rebooting my PC, rebooting my iPhone, swapped out USB cables, did a dance around my phone with gorilla suit on, but nothing works.

What else can I try?

**Comment by RealDyllon** [comment]
Have you tried port 9222 ?

**Comment by imadarif** [comment]
follow this 
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/181#issuecomment-652268303

**Comment by raygig** [comment]
It works! 

Comment #181 did it!

- Update iOS Webkit Debug Proxy: scoop update ios-webkit-debug-proxy
- Update Remotedebug iOS Webkit Adapter : npm update remotedebug_ios_webkit_adapter
- Keep iTunes open
