### ISSUE TITLE
"No websocket endpoint found" error

### ISSUE THREAD

**Issue by groverinho** [RemoteDebug/remotedebug-ios-webkit-adapter#197]
When I try to modify any css style on devtools I get "_No websocket endpoint found_" error.
It's was tested with iOS 13.4.1 and 13.5
Chrome Version 83.0.4103.61
**Any Advice or Idea?**

**Comment by miki995** [comment]
Same for me here.

**Comment by flamel2p** [comment]
Same for me here.

**Comment by marcusx2** [comment]
same

**Comment by sebysr** [comment]
As @groverinho pointed out, I faced the same issue when I changed the CSS style on devtools.
I tested on iOS 13.5.1 and Chrome Version 83.0.4103.106 And I **"solved"** in this way:

1. Go to Settings > Safari > Advanced and enable Web Inspector. 
2. When you enable web inspector on your iOS device select **Experimental Features**.
3. Enable CSS functionality, eg. @ page CSS at-rule support, CSS custom properties and Value, CSS typed OM, etc..
(I enabled also requestIdleCallback, webGPU, WebGL 2.0, but I don't know if they are necessary.)
4. Now you are free to test and debug your web-app.

Let me know your feedback please.

**Comment by sebysr** [comment]
On latest ios14, it seems stable now.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
