### ISSUE TITLE
Can only inspect pages on Safari not Chrome

### ISSUE THREAD

**Issue by blackmambahk** [RemoteDebug/remotedebug-ios-webkit-adapter#202]
Just installed all the latest packages, I am trying to debug Chrome on iOS 13.7 .

On a Mac (HighSierra) opened Chrome://inspect and the iPhone target shows up but it only list pages I have open on Safari on iOS and doesn't list any page open in Chrome, which is basically pointless.

Am I missing something, is this meant to be able to debug Chrome on iOS or is it just a way to use devtools to debug Safari?

**Comment by sebysr** [comment]
Hi @blackmambahk, according to my experience, if you have an ios device, this tool is only supported from safari.
For chrome browser there are some limitations related to the app.

Moreover, *Chrome 73 for iOS* adds a new inspect tool for developers to view JavaScript logs.
To enable JavaScript log collection, web developers can now visit and leave chrome://inspect open in the background of the iOS client. In another tab, reproduce the case for which you are interested. Then switch back to the chrome://inspect tab to view the collected logs. (Log collection will stop if the chrome://inspect page closes or navigates and logs will be lost as they are not persisted.)

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
