### ISSUE TITLE
Debug apps that run JavaScriptCore on Mac

### ISSUE THREAD

**Issue by derolf** [RemoteDebug/remotedebug-ios-webkit-adapter#204]
Is it possible to debug code that runs in JSC inside MacOS apps?

**Comment by SoylentGraham** [comment]
Safari can do this. You just need to ensure your app is signed (by anyone)

https://stackoverflow.com/questions/53695916/debugging-javascriptcore-with-safari-in-macos-app

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
