### ISSUE TITLE
Not seeing chrome(iPhone 8) anywhere

### ISSUE THREAD

**Issue by nirsharma** [RemoteDebug/remotedebug-ios-webkit-adapter#206]
I am trying to debug something in chrome for iPhone. It's not showing in Mac safari, Mac chrome, Mac Edge.

**Comment by kumail-raza** [comment]
The same issue I am facing, however I am able to resolve the issue for which I need to debug. I actually created a page with piece of code hosted it, the page shows the console message in HTML element.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
