### ISSUE TITLE
SSL Cert issue: WebSocket network error: The operation couldn’t be completed. (OSStatus error -9807.)

### ISSUE THREAD

**Issue by csimpi** [RemoteDebug/remotedebug-ios-webkit-adapter#208]
Hi,
everything looks good except I can't see the console logs at all. Only some error message appears, but nothing from the `console.log('Log it')`.

I think this is something with SSL. I have a valid HTTPS connection with the website on the device.

![image](https://user-images.githubusercontent.com/6192067/100900476-2fca8280-34c3-11eb-9684-80d8b6d5f1b0.png)

Networks tab works as expected.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
