### ISSUE TITLE
Unable to find ios_webkit_debug_proxy.exe when not installed with Scoop

### ISSUE THREAD

**Issue by elieux** [RemoteDebug/remotedebug-ios-webkit-adapter#209]
One might have ios_webkit_debug_proxy.exe installed via different means than Scoop. Would you be okay with searching both PATH and the pre-determined Scoop paths on Windows?

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
