### ISSUE TITLE
Listener not working on iOS 14.4

### ISSUE THREAD

**Issue by denisecastagna2** [RemoteDebug/remotedebug-ios-webkit-adapter#210]
I have two device (iphone and ipad) both with installed version iOS 14.4 and now no one is show in the devices list of chrome. Is it possible that is a problem of this version of iOS?

**Comment by ongkhua** [comment]
+1 same here

**Comment by hhhpw** [comment]
I have same question.
mac: 10.15.6 
iphone:14.4.1
I did with  README.md said.
but i can not find my phone is showed in devices.
I sure the computer and phone  are ok both

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
