### ISSUE TITLE
Issue with console and can't see the app console.log messages.

### ISSUE THREAD

**Issue by kumail-raza** [RemoteDebug/remotedebug-ios-webkit-adapter#211]
![image](https://user-images.githubusercontent.com/2698458/111470551-cc9aee00-8749-11eb-9de4-55babd68388b.png)

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
