### ISSUE TITLE
fyi complaint to the european unity

### ISSUE THREAD

**Issue by subjectdenied** [RemoteDebug/remotedebug-ios-webkit-adapter#212]
i'm personally fed up with the fact i can't debug a website/project i develop on any of my ios devices without buying a mac, and wrote an inquiry to my local european unity representant for it-topics about anticompetivie behaviour of apple. i will let you know, about any reply

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
