### ISSUE TITLE
Working with Simulator?

### ISSUE THREAD

**Issue by ekulabuhov** [RemoteDebug/remotedebug-ios-webkit-adapter#46]
Hi! I wonder if it works with Simulator? I've tried with iOS 10 Simulator and I see an empty list browsing to /json endpoint.

**Comment by auchenberg** [comment]
It should be. The simulator has to be started before the adapter is started, due to a limitation in `ios-webkit-debug-proxy`.

What happens if you start ios-webkit-debug-proxy directly?

**Comment by ekulabuhov** [comment]
This is likely related to: https://github.com/google/ios-webkit-debug-proxy/issues/185

I dug a bit deeper and it seems like `/json` on `ios-webkit-debug-proxy` is returning an empty list. At this point I'm quite certain that the problem is not related to this project. Thanks!

Simulator version: iOS 10.2 (14C89).

**Comment by artygus** [comment]
duplicate of #185

**Comment by auchenberg** [comment]
Closing as https://github.com/google/ios-webkit-debug-proxy/issues/185 is closed.
