### ISSUE TITLE
Does not show any devices in chrome dev tools

### ISSUE THREAD

**Issue by dmusicant** [RemoteDebug/remotedebug-ios-webkit-adapter#49]
I installed ioswebkit proxy debug and libmobiledevice (and the ios webkit proxy debug works - i tested it first). I then installed remotedebug-ios-webkit-adapter via the npm -g command and it installed without error. 

After starting up dev tools "chrome://inspect/#devices" and clicking "configure" and adding "localhost:9000", it shows the text "Remote Target #LOCALHOST" but nothing under it.

restarting chrome did not fix it.
Restarting remotedebug-ios-webkit-adapter did not fix it (nor choosing a diff port).

I don't see any errors.

remotedebug-ios-webkit-adapter keeps printing out:

    iosAdapter.getTargets
    http://127.0.0.1:9222/json

How do i figure out what's wrong?

**Comment by netpoetica** [comment]
I can confirm that I am able to see my device using ios_webkit_debug_proxy by itself, but it doesn't show up when booted through remotedebug-ios-webkit-adapter

**Comment by netpoetica** [comment]
I was able to fix this by following these steps https://github.com/google/ios-webkit-debug-proxy/issues/181#issuecomment-271857294

Basically, I had installed libimobiledevice@HEAD for ios-webkit-debug-proxy, but then when I came here, I decided to run `brew install libimobiledevice` which I assume is probably most recent release or something, which gives an error as per that comment above, and leads to empty list of inspectable pages.

I ended up having to do:

```
brew update
brew unlink libimobiledevice ios-webkit-debug-proxy
brew uninstall --force libimobiledevice ios-webkit-debug-proxy
brew install --HEAD libimobiledevice
brew install --HEAD ios-webkit-debug-proxy
```
Force uninstall was necessary because libimobiledevice was very, very sticky :o

Then, I ran 
```
remotedebug_ios_webkit_adapter --port=9000
```
and finally went to
```
chrome://inspect/#devices
```
where I was able to see my inspectable UIWebView from an iOS app on my iPhone.

**Comment by auchenberg** [comment]
@netpoetica Cool! I have updated the OSX instructions in the README. https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/commit/0531d6725b5955c32e91945a331466d18899920a

**Comment by zilahir** [comment]
i am still facing this issue, no devices shows up in the device list, even if i am having multiple attached tom my computer. :( any idea? i have followed the steps.

**Comment by Jorybraun** [comment]
Same recently tried to follow the install instructions but am not seeing any devices.

**Comment by netcinematics** [comment]
same error here (windows 10 to Fire tablet via usb).

**Comment by crossRT** [comment]
same problem here.
Any solution for this?

**Comment by sweetcornersyd** [comment]
Can anybody help with this problem? I have the same situation, but nothing helps me :( I see the only Android device in the chrome but not iPhone...

**Comment by shamoons** [comment]
I have the same issue - running Win10

**Comment by siddhantraut** [comment]
@netpoetica @auchenberg   can you please help us. 
I am also not getting app webview/  webpage opened in safari browser to open.

please find attached 
<img width="1636" alt="Screen Shot 2020-01-10 at 4 43 20 PM" src="https://user-images.githubusercontent.com/21220390/72188911-76098580-33c9-11ea-9b78-9dba81aaa62a.png">
screenshot.
