### ISSUE TITLE
Unknown compiler option 'types'.

### ISSUE THREAD

**Issue by CWBudde** [RemoteDebug/remotedebug-ios-webkit-adapter#50]
While trying to build the latest source code TypeScript exits with the error:

> Unknown compiler option 'types'.

and a few more errors like:

> src\adapters\adapter.ts(5,26): error TS2307: Cannot find module 'request'.
> src\adapters\adapter.ts(6,23): error TS2307: Cannot find module 'http'.
> ...

I'm using nodejs version 7.7.2 (The global typescript compiler has the version 2.2.1).

**Comment by auchenberg** [comment]
Fixed in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/commit/408c0b5acb91f679bea51d05fdd01d268f397471
