### ISSUE TITLE
npm version is broken

### ISSUE THREAD

**Issue by remcohaszing** [RemoteDebug/remotedebug-ios-webkit-adapter#51]
I installed the version from `npm` as described in the readme. This didn't even make web views show up in chrome://inspect. When I tried the version from master, it suddenly just works (except for some bugs, but it's totally workable).

It would be nice if the current state was published to npm.

**Comment by auchenberg** [comment]
v0.1.4 has been pushed to NPM. Enjoy :) https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/releases/tag/v0.1.4

**Comment by remcohaszing** [comment]
Thanks! 😄
