### ISSUE TITLE
Question: How to debug phoneGap production apps?

### ISSUE THREAD

**Issue by Risingson** [RemoteDebug/remotedebug-ios-webkit-adapter#53]
Should it be possible to debug a phonegap app webview with this?
I tried and the device was found but i did not see a screencast nor did i see entries in the console...

**Comment by auchenberg** [comment]
View views should be supported in general, as long as they are running in dev mode.

@Risingson Can you provide some details about your PhoneGap app? iOS version, etc?

**Comment by Risingson** [comment]
I tried on a iOS 9.x and iOS 10.x device (i read about iOS 10 on Windows might not work in the readme).
I needed to debug a deployed app...

**Comment by auchenberg** [comment]
PhoneGap App, can't at the moment be debugged. See https://github.com/phonegap/phonegap-app-developer/issues/49

Production builds of PhoneGap apps can't be debugged either, so you would need to make a dev/debug build of your app, before remote debugging capabilities are enabled. See https://crosswalk-project.org/documentation/android/android_remote_debugging.html#Enable-debugging-at-build-time-for-Android,
