### ISSUE TITLE
Can I debug production web views?

### ISSUE THREAD

**Issue by satlxq** [RemoteDebug/remotedebug-ios-webkit-adapter#55]
I don't know whether this issue exists in other iOS versions, With remotedebug, I can debug pages in safari, but couldn't debug any pages in webview.

**Comment by auchenberg** [comment]
Are you trying to debug a webview in a production app or while in development? Only development apps can be remote debugged.

**Comment by satlxq** [comment]
Thanks. 
Get it, I am debugging on a production app.

**Comment by fishbone1** [comment]
What do you mean by "development" or "production" app? I have a Cordova app. Where can I see if it's built as a development app? I built a signed IPA file and provide it via company app store. I wonder if this makes the app a "production" app automatically (?) Is this related to "Debug" and "Release" build profiles?
