### ISSUE TITLE
Screencast: Emulate Mouse scrolling when screencasting

### ISSUE THREAD

**Issue by dotnetshadow** [RemoteDebug/remotedebug-ios-webkit-adapter#56]
Hi there,

The new version works a treat fixed #52 for me.

One issue I did notice was that I'm unable to use my mouse to scroll in chrome are there limitations?

I tried with middle mousewheel and also tried dragging up a page using the left mouse button but couldn't get it working?

![image](https://cloud.githubusercontent.com/assets/296247/25789422/e0af206c-33f3-11e7-96f7-6422fc52386f.png)

**Comment by auchenberg** [comment]
When are you trying to scroll? When screencasting?

**Comment by dotnetshadow** [comment]
yep like I can scroll on mobile that's fine and in chrome it scrolls.

But if I try to scroll in chrome nothing happens

So I basically just do the following:
1) Run ios webkit adapter
2) Go to Remote Targets select the page that I'm trying to view
3) It's loads I can inspect, I can click around
4) Now if I have a long page I need to scroll down I can't actually do it on windows I need to scroll on my mobile.

**Comment by auchenberg** [comment]
Ah. I see. At this point I haven't found a way to emulate mouse scrolling. This is show it's currently working. https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/master/src/protocols/ios/ios.ts#L481

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
