### ISSUE TITLE
can debug wkwebview?

### ISSUE THREAD

**Issue by lcat** [RemoteDebug/remotedebug-ios-webkit-adapter#59]
In a uiwebview APP can be normal debug. But in the wkwebview, dos not work

ios_webkit_debug_proxy 1.7.1
libimobiledevice v1.2.1
libplist v1.12

**Comment by auchenberg** [comment]
@lcat Can you debug `wkwebview` from Safari on OSX?

**Comment by lcat** [comment]
@auchenberg not work.

**Comment by auchenberg** [comment]
Try http://stackoverflow.com/questions/25200116/how-to-show-the-inspector-within-your-wkwebview-based-desktop-app or http://stackoverflow.com/questions/25871586/how-to-debug-javascript-code-inside-a-wkwebview

Is this a `wkwebview` running on iOS or MacOS?

**Comment by auchenberg** [comment]
Using to due lack of activity.
