### ISSUE TITLE
Can't see my page on Chrome but 9222

### ISSUE THREAD

**Issue by liaolunhui** [RemoteDebug/remotedebug-ios-webkit-adapter#6]
![image](https://cloud.githubusercontent.com/assets/13741751/20793124/7ada0cbc-b800-11e6-8b4b-47bf3de42690.png)
![image](https://cloud.githubusercontent.com/assets/13741751/20793132/88b6d194-b800-11e6-924c-924e14cc3936.png)
![image](https://cloud.githubusercontent.com/assets/13741751/20793153/9d9ee074-b800-11e6-8e09-59fd63f8314a.png)
As the picture above, I run this tool and config chrome . But it doesn't works.
But it works  via localhost:9222

**Comment by auchenberg** [comment]
You should use Chrome Canary and go to `chrome://inspect` who has the new Network discovery feature

![screen shot 2016-12-01 at 1 19 04 pm](https://cloud.githubusercontent.com/assets/173559/20813013/c15c7f90-b7c8-11e6-80d8-0e360c9f3eb8.png)

**Comment by liaolunhui** [comment]
Thanks,I can see my safari page.
![image](https://cloud.githubusercontent.com/assets/13741751/20835899/f05940de-b8d7-11e6-8dcb-063b04e8337d.png)

But I got this error when I click `inspect`

![image](https://cloud.githubusercontent.com/assets/13741751/20835877/d6ea7cbc-b8d7-11e6-814e-74414b364d2f.png)

**Comment by auchenberg** [comment]
@liaolunhui Looks like you are using an old build. Please upgrade.

**Comment by liaolunhui** [comment]
Do you mean old Chrome Canary ? I installed the latest version. Can you tell me what version are you using?

**Comment by auchenberg** [comment]
@liaolunhui No I mean you need to update to the latest version of this adapter, as the issue you have was fixed in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/commit/06edf894faabb03eeb8a373ee18efd75e2ccbd8a

**Comment by liaolunhui** [comment]
I cloned the latest version,the code is as you mentioned. But it still navigated me to `chrome-devtools://devtools/?remoteFrontend=true&dockSide=undocked`

**Comment by auchenberg** [comment]
Interesting @liaolunhui. Can you go to `http://localhost:9000/json` while the adapter is running and dump the output here? What version of Chrome Canary are you using?
