### ISSUE TITLE
Console doesn't work...

### ISSUE THREAD

**Issue by kriserickson** [RemoteDebug/remotedebug-ios-webkit-adapter#62]
Almost everything else works (elements including device preview, sources, network, application -- memory and performance don't work either but they aren't nearly as important).  Console does not log console messages and any attempts to hit enter are ignored, so nothing is evaluated from the console command line.

**Version Info**
libimobiledevice HEAD-53fede0_2
ios-webkit-debug-proxy HEAD-55d0a95

remotedebug-ios-webkit-adapter@0.1.9

macOS 10.12.5
Tried on iOS 10.3.3 and 10.3.2, both in Safari and on a Cordova Project.

Nothing from the logs but:

```
$ remotedebug_ios_webkit_adapter --port=9000
remotedebug-ios-webkit-adapter is listening on port 9000
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
New websocket connection to /ios_74887fa705c68ccc6520c8edba9128dbd18254d9/PID:336
Connection established to ws://127.0.0.1:9102/devtools/page/1
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets


```

**Comment by auchenberg** [comment]
Thanks for the report @kriserickson! This is most likely because Chrome's logging API has changed recently. 

Can you try to start the adapter with tracing enabled by running `DEBUG=remotedebug remotedebug_ios_webkit_adapter --port=9000` and paste the putout here?

**Comment by kriserickson** [comment]
Wow, you are on this fast, and even without the console support this is fantastic tool (I know I should be able to use the Safari Web Inspector but the way source code is organized and the inability to do cmd-O to go to a file makes it almost unusable for me).  Here is the log zipped up -- if you need a longer time frame or me to do anything special after launching let me know, happy to help in any way.   

[remotedebug.zip](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/files/1078777/remotedebug.zip)

**Comment by auchenberg** [comment]
Great thanks! I hope to have a look over the next coming days!

**Comment by auchenberg** [comment]
Fixed in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/commit/6388b719fa3e1a712ca235c68aa6db47dfe47674

@kriserickson Please try to pull down master and build from sources, then you should have a working console.

**Comment by kriserickson** [comment]
@auchenberg it's half fixed in that it now displays console messages, it just doesn't evaluate anything from the console (i.e. entering 1+1 and hitting enter does nothing, you don't even get a new line).

Here is the log from running it, and entering '1+1<enter>' on the console.

[remote-debug.zip](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/files/1095945/remote-debug.zip)

**Comment by auchenberg** [comment]
Gotcha. Some more API mapping to do then :)

**Comment by kriserickson** [comment]
@auchenberg  Anything I can do to help?  I'm going to be in iOS safari debuging land for the next few days (and am currently running remotedebug-ios-webkit-adapter 90% of the time and only switching back Safari Webkit when I need to do interactive debugging).  From my quick debugging:

'Runtime.evaluate' isn't called, but 'Runtime.compileScript' is...   With the message:

```
{ 
  id: number,
  method: 'Runtime.compileScript',
  params:    { 
     expression: string,
     sourceURL: string,
     persistScript: boolean,
     executionContextId: number 
  } 
}
```

and looking into https://chromedevtools.github.io/devtools-protocol/v8/Runtime/#method-compileScript, it isn't clear what to do?

**Comment by auchenberg** [comment]
I think I managed to get the basic use cases covered by calling `Runtime.evaluate` in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/commit/5d41e65d8a38ac8f8b4d0abe612ad234a88a8140

I've noticed that calling `alert` is a blocking operation.

@kriserickson Can you give it a try?

**Comment by kriserickson** [comment]
@auchenberg Works perfectly!   Awesome, thanks so much.  I wish I could have realized that changing the message type would trigger the evaluate to run.  I got about halfway there, and was trying to do the evaluate in the compileScript handler...

**Comment by auchenberg** [comment]
Yay! 🔥

That would probably be the more correct approach, hereby cleaned up.
