### ISSUE TITLE
Windows not able to inspect IOS 10.x

### ISSUE THREAD

**Issue by green3g** [RemoteDebug/remotedebug-ios-webkit-adapter#68]
I'm running this program trying to inspect but in the chrome devices page, it does not show the device list. This is what I'm seeing:

![image](https://user-images.githubusercontent.com/5471079/28223347-af7a98e2-6890-11e7-9829-5017967a598e.png)

Meanwhile, the ios adapter messages continue to get logged.

![image](https://user-images.githubusercontent.com/5471079/28223373-c08ddcb6-6890-11e7-87d8-dc884f524c99.png)

This might have to do with the remotedebug proxy bundled I think I have read. But I have successfully gotten it to connect using the windows binary for the proxy, so I'm not sure what my issue is.

**Comment by auchenberg** [comment]
Have you tried downloading the HEAD release of https://github.com/artygus/ios-webkit-debug-proxy-win32, and replace the binary inside node_modules/node_modules/vs-libimobile/lib/?

**Comment by green3g** [comment]
That was easy! Thanks! I am getting errors like error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object] but its working!

**Comment by auchenberg** [comment]
Cool, glad it worked @roemhildtg! We still need to figure out a better Windows story.

**Comment by green3g** [comment]
Hey, @auchenberg I'm running into this issue again, this time after updating to ios 11. Is this version not supported yet?

**Comment by auchenberg** [comment]
@roemhildtg Try to follow the instructions in https://github.com/google/ios-webkit-debug-proxy#installation which now has Windows build, and repeat the last steps as last time.

If this doesn't work, please open a new iOS 11 issue, and we'll have a look.

**Comment by taneltm** [comment]
I think this ticket can be closed. Version 0.2.1 fixes iOS 10 issue.
@roemhildtg check #79

**Comment by gety9** [comment]
@auchenberg 

Could you explain which files exactly i need to replace in /node_modules/vs-libimobile/lib/?
[Here is what i have](https://puu.sh/y12fs/5e950042b3.png)

p.s. I just installed IOS 11.x on one of my iphones for testing. And Remote target list is empty. It works with my IOS 10.x iphone correctly though.
I am using windows 10.

**Comment by auchenberg** [comment]
@gety9 Download the latest release from https://github.com/google/ios-webkit-debug-proxy/releases, unzip into a folder, and copy paste the full contents into`remotedebug-ios-webkit-adapter/node_modules/vs-libimobile`

**Comment by danrossi** [comment]
I've done the above and get this error. 

```
remotedebug-ios-webkit-adapter failed to run with the following error: adapter.spawnProcess.close, code=3221225595
```

**Comment by danrossi** [comment]
This has been an absolute dead end for me. If I try the proxy directly. I can get everything but console logs working in chrome. This won't even run with the updated proxy copied across requiring to debug the code somehow directly. 

I will attempt weinre instead to prevent anymore wasted time sadly.

**Comment by danrossi** [comment]
All the dll files from the proxy binary need to be copied across. Then it will start working. 

I get this however. 

```
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
````

**Comment by auchenberg** [comment]
See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-351472710
