### ISSUE TITLE
Memory Tab

### ISSUE THREAD

**Issue by jamime** [RemoteDebug/remotedebug-ios-webkit-adapter#69]
Is it possible to take memory snapshots? It doesn't seem to work.

**Comment by auchenberg** [comment]
The Profiling APis between Chrome and Webkit has diverged quite a bit, so I don't think it would be possible, but I haven't analyzed the API differences yet.

You can help by diving into the APIs on http://compatibility.remotedebug.org

**Comment by suchipi** [comment]
The Profiling tab also doesn't work, but judging from http://compatibility.remotedebug.org/Profiler it doesn't look like it's possible to make it work, since Safari doesn't support the APIs.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
