### ISSUE TITLE
Networking Tab, all time is pending, most size is 0 bytes...

### ISSUE THREAD

**Issue by kriserickson** [RemoteDebug/remotedebug-ios-webkit-adapter#70]
On the networking tab the Size for most requests is 0 bytes, and the Time is pending for all of the requests.  Clicking on the request you can view headers, preview, response, timing etc.  See attachment (note, all of these requests have loaded and are inspectable at this point).

![image](https://user-images.githubusercontent.com/325934/28799881-2ad7eb90-75ff-11e7-8b10-67cd5871e4ae.png)

**Comment by auchenberg** [comment]
Thanks for the report! Most likely caused by a divergence in the Network APis between Chrome and Webkit. The differences needs to be investigated. A good starting point by browsing http://compatibility.remotedebug.org/Network, if times allows it @kriserickson

**Comment by LeonSolisPedro** [comment]
Any news about this? 😊

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
