### ISSUE TITLE
Styling elements doesnt work due to UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by gaiagilder** [RemoteDebug/remotedebug-ios-webkit-adapter#71]
I'm working in Ubuntu 64 with chrome dev tools and iphone 4 with ios 10.3,
i get this error when i try to inspect  only certain elements,

>  (node:8156) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'length' of null

>  (node:15128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Could be a conflict with some library?
I tried with others apps but there were no problems.

**Comment by auchenberg** [comment]
Can I get you to run `DEBUG=remotedebug remotedebug_ios_webkit_adapter` which should able verbose logging, and paste the result in here?

**Comment by gaiagilder** [comment]
thanks,

[allout.txt](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/files/1261256/allout.txt)

**Comment by auchenberg** [comment]
Looks like it's the `CSS.getMatchedStylesForNode","params":{"nodeId":51}}` call that fails, triggered by https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/master/src/protocols/ios/ios.ts#L652

**Comment by auchenberg** [comment]
Tried handlling the case in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/commit/631a8ffffa46b3980ef1a5a250bb85c97b9e0eac

@gaiagilder Can I get you to try to pull master, and follow these instructions to run the local build and let me know how it works? https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#how-to-contribute

**Comment by gaiagilder** [comment]
It looks the same

[allout.txt](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/files/1261713/allout.txt)

I'll try to isolate code in my app to find what is causing this

**Comment by auchenberg** [comment]
That would be much easier than me trying to guess

**Comment by gaiagilder** [comment]
I think too many times the style of the element in question were overwritten via js and even some redundancy was causing this exception, i just ordered the css rules and deleted what was not needed and so so i solved my problem, perhaps it was impossible to calculate exact rules during reading, sorry I do not know if i will be able to provide a more detailed answer.

**Comment by auchenberg** [comment]
Alright. Closing for now then.
