### ISSUE TITLE
Suggestion for docs

### ISSUE THREAD

**Issue by OliverJAsh** [RemoteDebug/remotedebug-ios-webkit-adapter#72]
Hi there,

Thanks for the fantastic tool.

I had some trouble getting it work after following the docs. Turns out I needed to follow these steps:

- Enable `Web Inspector` setting in Safari preferences
- Open Safari on Mac to inspect the device through Safari dev tools and follow instructions to trust device

After following these steps, my device showed up!

May I suggest we add these instructions to the README?

Thanks,
Oliver

**Comment by auchenberg** [comment]
Hi @OliverJAsh 

Great suggestions! Do you have time to open a PR with the changes to the README? https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/master/README.md

**Comment by OliverJAsh** [comment]
See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/pull/73

**Comment by auchenberg** [comment]
Awesome @OliverJAsh Thanks for the contribution!

**Comment by Justin-Maxwell** [comment]
Hi.

It's not clear if this is a requirement to do both, or either/or.  I understand the need for the first item, but not the second.  I had tried Mac Safari a few days ago with this phone, so I can't speak to whether or not the second step is (always) required, but if it is, there should be '..., and' on the first line, and perhaps a short reason for the second line.  

On my Linux setup, I get prompted to trust the computer as expected, but perhaps the Mac Safari inspection makes some sort of one-time change on the phone?

Didn't seem significant enough to open a new issue.

FWIW - This tool (with it's deps) is a life-saver!!!  Thank you!

**Comment by auchenberg** [comment]
@Justin-Maxwell I've made the instructions more clear here https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/commit/87e10b91bdad72b35b450ffce2c838b558b69255, feel free to contribute!
