### ISSUE TITLE
persistent / autoreload inspector once app is up again on remote device

### ISSUE THREAD

**Issue by damianobarbati** [RemoteDebug/remotedebug-ios-webkit-adapter#75]
This project is amazing, one problem though: every time the app is closed on the emulator the inspector loose connection but is not able to recover it once the app is back up again.

This make development painful because you stuck in the loop:
. build your android app and run it on the emulator
. reload chrome://inspect 
. click "inspect device"
. debug your app
. again from 1

Most of time is wasted in reopening the inspector and not actually working 😔

**Comment by auchenberg** [comment]
Interesting case @damianobarbati 

If you go to `http://localhost:9000/json` and compare the output, it would be good to know if the ID's stay the same, as we then have an opportunity to reconnect.

**Comment by damianobarbati** [comment]
@auchenberg thanks for helping!

Here's what I get on android device (real one), before and after redeploy:
```
[]
```

Here's what I get on ios device (real one), before and after redeploy:
```
[
    {
        "devtoolsFrontendUrl": "https://chrome-devtools-frontend.appspot.com/serve_file/@7d149ef5473e980f0b3babd4d0f2839cb9338e73/inspector.html?experiments=true&remoteFrontend=screencast&ws=localhost:9000/ios_670e902f0fb8cf7ccd56c40916322c8bdc0888d0/PID:1618",
        "faviconUrl": "",
        "thumbnailUrl": "/thumb/file:///",
        "title": "user",
        "url": "file:///",
        "webSocketDebuggerUrl": "ws://localhost:9000/ios_670e902f0fb8cf7ccd56c40916322c8bdc0888d0/PID:1618",
        "appId": "PID:1618",
        "id": "PID:1618",
        "adapterType": "_ios_670e902f0fb8cf7ccd56c40916322c8bdc0888d0",
        "type": "page",
        "metadata": {
            "deviceId": "670e902f0fb8cf7ccd56c40916322c8bdc0888d0",
            "deviceName": "damz",
            "url": "127.0.0.1:9101",
            "version": "11.0.1"
        }
    }
]
```
```
[
    {
        "devtoolsFrontendUrl": "https://chrome-devtools-frontend.appspot.com/serve_file/@7d149ef5473e980f0b3babd4d0f2839cb9338e73/inspector.html?experiments=true&remoteFrontend=screencast&ws=localhost:9000/ios_670e902f0fb8cf7ccd56c40916322c8bdc0888d0/PID:1627",
        "faviconUrl": "",
        "thumbnailUrl": "/thumb/file:///var/containers/Bundle/Application/AC1BF703-8A72-4F9E-9739-45C44D1931CA/adminify.app/www/index.html",
        "title": "user",
        "url": "file:///var/containers/Bundle/Application/AC1BF703-8A72-4F9E-9739-45C44D1931CA/adminify.app/www/index.html",
        "webSocketDebuggerUrl": "ws://localhost:9000/ios_670e902f0fb8cf7ccd56c40916322c8bdc0888d0/PID:1627",
        "appId": "PID:1627",
        "id": "PID:1627",
        "adapterType": "_ios_670e902f0fb8cf7ccd56c40916322c8bdc0888d0",
        "type": "page",
        "metadata": {
            "deviceId": "670e902f0fb8cf7ccd56c40916322c8bdc0888d0",
            "deviceName": "damz",
            "url": "127.0.0.1:9101",
            "version": "11.0.1"
        }
    }
]
```

**Comment by auchenberg** [comment]
Ah, the adaptor won't work with Android devices, as they will work natively with Chrome.

I see the problem. We include the `"id": "PID:1618",` which is unique to your app instance in `"webSocketDebuggerUrl"` which pass to Chrome DevTools, so then the front-end tries to reconnect it can't, as the `id` has changed.

I don't think there will be an easy way to fix this....

**Comment by damianobarbati** [comment]
> Ah, the adaptor won't work with Android devices, as they will work natively with Chrome.

Any chance to auto-reload inspector for Android devices at least?

Cordova apps debugging is so painful 😔

**Comment by auchenberg** [comment]
@damianobarbati I don't control how chrome://inspect works inside Chrome, so no. You can probably do somesort of live reloading inside your Cordova app that would keep the app running, and therefore keep the debugging session alive.

https://github.com/nparashuram/cordova-plugin-browsersync

**Comment by damianobarbati** [comment]
Thanks @auchenberg, I'll give it a shot!
