### ISSUE TITLE
After updating to iOS 11.1 No Remote Targets show up in Chrome.

### ISSUE THREAD

**Issue by kriserickson** [RemoteDebug/remotedebug-ios-webkit-adapter#76]
Was working fine, then updated to iOS 11.1 and there is now nothing in the DevTools Devices.

Device: iPhone 5s
OS: macOS 10.12.6

Don't know if this helps at all but the debug output running from master is:

> remotedebug-ios-webkit-adapter@0.2.1 start /Users/kris/projects/node/remotedebug-ios-webkit-adapter
> gulp build && node out/index.js

[15:38:22] Using gulpfile ~/projects/node/remotedebug-ios-webkit-adapter/gulpfile.js
[15:38:22] Starting 'build'...
[15:38:24] Finished 'build' after 1.88 s
  remotedebug server.run, port=9000 +0ms
  remotedebug server.setupHttpHandlers +7ms
  remotedebug iOSAdapter.getProxySettings +10ms
  remotedebug iOSAdapter.getProxyPath +0ms
  remotedebug adapterCollection.start Map {} +6ms
  remotedebug adapter.start { port: 9100,
  proxyExePath: '/usr/local/bin/ios_webkit_debug_proxy',
  proxyExeArgs: [ '--no-frontend', '--config=null:9100,:9101-9201' ],
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +2ms
  remotedebug adapter.spawnProcess, path=/usr/local/bin/ios_webkit_debug_proxy +2ms
  remotedebug adapter.spawnProcess.stderr, data=Could not connect to lockdownd. Exiting.: Operation now in progress
  remotedebug  +21ms
  remotedebug adapter.spawnProcess.stderr, data=Unable to attach d926ccb0809a0c2bb5b05ed3374f1a6925b05d25 inspector
  remotedebug  +1ms
  remotedebug server.startTargetFetcher +192ms
remotedebug-ios-webkit-adapter is listening on port 9000
  remotedebug server.http.endpoint/json/version +359ms
  remotedebug server.http.endpoint/json +14ms
  remotedebug iOSAdapter.getTargets +1ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +2ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +2ms
  remotedebug iOSAdapter.getTargets +0ms

**Comment by auchenberg** [comment]
Fixed in the latest build of `ios-webkit-debug-proxy` on Mac: 

https://github.com/google/ios-webkit-debug-proxy/issues/225

**Comment by auchenberg** [comment]
@kriserickson Just re-read the issue again. Did you run `11.0` before where things worked?
