### ISSUE TITLE
Chrome DevTools doesn't load from China on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by sanmiao11** [RemoteDebug/remotedebug-ios-webkit-adapter#78]
Hi,
I can see remote target list at 'chrome://inspect/#devices', however the pop-up page is empty when I click the 'inspect' under the certain target.
Is there anything wrong?

![image](https://user-images.githubusercontent.com/7659135/31657983-636fd17a-b362-11e7-8ed9-bc14ca362c58.png)

![image](https://user-images.githubusercontent.com/7659135/31657561-43adbb0a-b361-11e7-8eb8-a8559b1cb300.png)

**Comment by auchenberg** [comment]
Looks like Chrome fails to load the Chrome DevTools frontend. Are your network behind some sort of proxy?

**Comment by auchenberg** [comment]
Closing as this is a problem with Chrome DevTools, and not this adaptor. My advice would be to use a VPN from China.
