### ISSUE TITLE
Styles pane get stuck when active element disappears

### ISSUE THREAD

**Issue by pandreyn** [RemoteDebug/remotedebug-ios-webkit-adapter#80]
When in ChromeDevTools in Elements tab selected element disappears (for example some modal window) got error "**UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'matchedCSSRules' of undefined**".
After that Style tab stops updating(when I choose different elements in Elements tab) until I restart adapter.

**Comment by pandreyn** [comment]
After investigation I've found out that it is enough to add check that result is not empty to **onGetMatchedStylesForNodeResult** 
Created PR #81

**Comment by auchenberg** [comment]
@pandreyn Made a new release, so this has landed. Thanks for the help!
