### ISSUE TITLE
Windows 10, IOS 10.X Chrome devtools doesn't show any devices (DEBUG Included, Replaced proxy binary to the newest)

### ISSUE THREAD

**Issue by gilboz** [RemoteDebug/remotedebug-ios-webkit-adapter#82]
Hi I have followed the instructions on how to install and run, and also looked on all the issues with the same topic but nothing seem to work for me..
references:
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/68
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/52
I have downloaded the latest binary for the proxy and installed it in the correct path, 
I am getting the error

> error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]

As others do, but I am not able to see the device in my chrome devices?
Here is a screen shot:
<a href="https://ibb.co/gZXzBR"><img src="https://preview.ibb.co/f2wRrR/scrnshot.jpg" alt="scrnshot" border="0"></a>

Here is the output of debug running the adapter on port 9988 (9000 gave same result)
```
remotedebug_ios_webkit_adapter --port=9988
  remotedebug server.run, port=9988 +0ms
  remotedebug server.setupHttpHandlers +3ms
  remotedebug iOSAdapter.getProxySettings +5ms
  remotedebug iOSAdapter.getProxyPath +1ms
  remotedebug adapterCollection.start Map {} +2ms
  remotedebug adapter.start { port: 10088,
  proxyExePath: 'C:\\Users\\-\\AppData\\Roaming\\npm\\node_modules\\remotedebug-ios-webkit-adapter\\node_modules\\vs-libimobile\\lib\\ios_webkit_debug_proxy.exe',
  proxyExeArgs: [ '--no-frontend', '--config=null:10088,:10089-10189' ],
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +1ms
  remotedebug adapter.spawnProcess, path=C:\Users\-\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\lib\ios_webkit_debug_proxy.exe +2ms
  remotedebug server.startTargetFetcher +206ms
remotedebug-ios-webkit-adapter is listening on port 9988
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +7ms
  remotedebug iOSAdapter.getTargets +1ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +12ms
  remotedebug iOSAdapter.getDeviceInfoPath +2ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.start { port: 10089,
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +7ms
  remotedebug adapter.start: Skip spawnProcess, no proxyExePath available +1ms
  remotedebug adapter.getTargets, metadata=[object Object] +0ms
  remotedebug server.http.endpoint/json/version +2s
  remotedebug server.http.endpoint/json +3ms
  remotedebug iOSAdapter.getTargets +1ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +3ms
  remotedebug iOSAdapter.getDeviceInfoPath +1ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +6ms
  remotedebug iOSAdapter.getTargets +2s
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +8ms
  remotedebug iOSAdapter.getDeviceInfoPath +1ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +310ms
  remotedebug server.http.endpoint/json/version +4ms
  remotedebug server.http.endpoint/json +0ms
  remotedebug iOSAdapter.getTargets +1ms
iosAdapter.getTargets
  remotedebug server.startTargetFetcher.fetched.0 +5ms
  remotedebug iOSAdapter.getDeviceVersion +1ms
  remotedebug iOSAdapter.getDeviceInfoPath +1ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +7ms
  remotedebug server.http.endpoint/json +2s
  remotedebug iOSAdapter.getTargets +3ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +4ms
  remotedebug iOSAdapter.getDeviceVersion +6ms
  remotedebug iOSAdapter.getDeviceInfoPath +0ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +15ms
  remotedebug server.http.endpoint/json/version +2s
  remotedebug server.http.endpoint/json +3ms
  remotedebug iOSAdapter.getTargets +2ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +3ms
  remotedebug iOSAdapter.getDeviceInfoPath +0ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +8ms
  remotedebug iOSAdapter.getTargets +608ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +8ms
  remotedebug iOSAdapter.getDeviceInfoPath +1ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +13ms
  remotedebug server.startTargetFetcher.fetched.0 +2ms
  remotedebug server.http.endpoint/json +1s
  remotedebug iOSAdapter.getTargets +2ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +6ms
  remotedebug iOSAdapter.getDeviceVersion +4ms
  remotedebug iOSAdapter.getDeviceInfoPath +1ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +7ms
  remotedebug server.stop +1s
  remotedebug server.stopTargetFetcher +3ms
  remotedebug adapterCollection.stop +2ms
  remotedebug adapter.stop +2ms
  remotedebug adapter.stop +3ms
```

**Comment by auchenberg** [comment]
Can you try to run `,
  proxyExePath: 'C:\\Users\\-\\AppData\\Roaming\\npm\\node_modules\\remotedebug-ios-webkit-adapter\\node_modules\\vs-libimobile\\lib\\ios_webkit_debug_proxy.exe` directly from your command line, and see if any errors are shown?

**Comment by davidgeorgehope** [comment]
I also have this problem.

error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
Terminate batch job (Y/N)? Y




PS C:\Users\DJHope> C:\\Users\\DJHope\\AppData\\Roaming\\npm\\node_modules\\remotedebug-ios-webkit-adapter\\node_modules
\\vs-libimobile\\lib\\ios_webkit_debug_proxy.exe
Listing devices on :9221
Connected :9222 to iPhone (f5efea398ea01319e8f5788e8829ad265538ae61)
PS C:\Users\DJHope>

**Comment by freimuth82** [comment]
I have the same problem, no device gets listed. I have two iPads connected, one iPad Air 2 with iOS11.0 and one old iPad with iOS 9.3.5. I get both logs in the command line over and over like @appdynamicsdh .  Executing ios_webkit_debug_proxy.exe directly from the installed path shows this:

```
C:\Users\alex\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\lib> .\ios_webkit_debug_proxy.exe
Listing devices on :9221
socket_receive_timeout: fd=756 recv returned 0
Could not connect to lockdownd. Exiting.: No error
Unable to attach 06a030cf12c08e30e022a82dc86ebc461fccf1be inspector
Connected :9222 to iPad (old) (9ba05eac49c43dae86ca983edbc29bdec59e7c45)
```
Then I see the old iPad, but not the new one with iOS 11.

I downloaded the latest version of the ios_webkit_debug_proxy (1.8) and put it into almost the same path and executed it like the other version above and it connects both iPads. I also changed the path as suggested in the comment here https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-351472710 - but that does lead finally to the same problem: I always see:

```
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
```
Anything else I can do to provide more hopefully helpful information on this topic?

**Comment by auchenberg** [comment]
See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-351472710

**Comment by vaneeckhoutnicolas** [comment]
Hello Team,

I've tried the above steps but I'm still encountering the "error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]" while plugin my iPhone X without seeing any device on chrome inspect section.

Any idea?

Thanks,
Nico

**Comment by vaneeckhoutnicolas** [comment]
Thanks! I succeeded to configure :)
