### ISSUE TITLE
WkWebKit stopped showing on chrome://inspect/#devices on ios 11 and Ubuntu 16.04.03

### ISSUE THREAD

**Issue by tomeraz** [RemoteDebug/remotedebug-ios-webkit-adapter#85]
Setup:
ios 11 - Ipad Pro, Iphone, Ipad
Ubuntu 16.04.03

on ios 10 it's possible to see WkWebkit pages on chrome://inspect#devices
on ios 11 WkWebViews don't show, even though Safari pages are shown.

Anything I can do to make it show again?

**Comment by fab971** [comment]
Same for me with ios 10.2 version on Mac. It suddenly stop working

**Comment by auchenberg** [comment]
You can't debug webviews in published app from the App Store. If your app is using the development profile this should be possible. Try using https://github.com/google/ios-webkit-debug-proxy/ directly to see if your webview shows up.

**Comment by Matt-Jensen** [comment]
Experiencing same issue discovering devices in Chrome.  I've successfully connected a webview using ios-webkit-debug-proxy and I'm able to see my devices at localhost:9100 with remotedebug.

iOS 11.2
macOS 10.13
Chrome (Canary): 67.0.3370.0

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
