### ISSUE TITLE
how can i debug wechat html 

### ISSUE THREAD

**Issue by guider** [RemoteDebug/remotedebug-ios-webkit-adapter#86]
how can i debug wechat html  use remotedebug-ios-webkit-adapter?

**Comment by auchenberg** [comment]
@guider Can you elaborate more on what "wechat html" is? Mini programs?

**Comment by ghost** [comment]
Same issue here. Namely, when debugging a hybrid app, what should i do with remotedebug-ios-webkit-adapter. After running remotedebug-ios-webkit-adapter, i find that it only could debug a html page with running in iOS safari browser. However, i would like to debug a webview page of hybrid app. So, i become increasingly frustrated with running into the above issue.

**Comment by auchenberg** [comment]
You can't debug webviews in published app from the App Store. If your app is using the development profile this should be possible. Try using https://github.com/google/ios-webkit-debug-proxy/ directly to see if your webview shows up.
