### ISSUE TITLE
ubuntu 16.04 - cli run fails  adapter.spawnProcess.close, code=255

### ISSUE THREAD

**Issue by rowntreerob** [RemoteDebug/remotedebug-ios-webkit-adapter#87]
Install and run tests (gulp test) is fine but  from the CLI the run process is throwing error
Port 9000 is free

no idea what is wrong?

```
rob@ ios-webkit-debug-proxy$ remotedebug_ios_webkit_adapter --port=9000 --verbose

remotedebug-ios-webkit-adapter failed to run with the following error: adapter.spawnProcess.close, code=255
```
gulp test  OK

```
11:58:32] Starting 'build-tests'...
[11:58:34] Finished 'build-tests' after 1.9 s
[11:58:34] Starting 'test'...


  Proxy/Protocol/Target
    connectTo()
      ✓ establishes a connection to the real target websocket
Connection not yet open, buffering message.
Connection not yet open, buffering message.
Connection established to ws://localhost:8080
      ✓ buffers messages to target before connect and then sends them on connect
    forward()
Connection established to ws://localhost:8080
      ✓ emits message from tools to target
Connection established to ws://localhost:8080
      ✓ emits message from target to tools
    fireEventToTools()
Connection established to ws://localhost:8080
      ✓ sends the correct data format
    fireResultToTools()
Connection established to ws://localhost:8080
      ✓ sends the correct data format
    callTarget()
Connection established to ws://localhost:8080
      ✓ sends a request to the target without calling back to the tools
Connection established to ws://localhost:8080
      ✓ rejects the promise on an error from the target
    addMessageFilter()
Connection established to ws://localhost:8080
      ✓ filter is called and modified on message from tools
Connection established to ws://localhost:8080
      ✓ filter is called and modified on message from target
Connection established to ws://localhost:8080
      ✓ filter is called and modifies the response to a request from tools
    updateClient()
Connection established to ws://localhost:8080
Socket is closed
      ✓ message is sent to new tools
    replyWithEmpty()
Connection established to ws://localhost:8080
Connection established to ws://localhost:8080
      ✓ empty message is sent to tools
```

**Comment by auchenberg** [comment]
Do you have `ios-webkit-debug-proxy` installed as outline in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#1-install-dependencies?

Can you start `ios-webkit-debug-proxy` from your terminal by itself?

**Comment by rowntreerob** [comment]
thx for prompt rply .

i discovered DEBUG= on the node CLI ... 

it all OK.. thank u 

no ios device = RC 255

  remotedebug iOSAdapter.getProxySettings +2ms
  remotedebug iOSAdapter.getProxyPath +0ms
  remotedebug adapterCollection.start Map {} +3ms
  remotedebug adapter.start { port: 9100,
  proxyExePath: '/usr/local/bin/ios_webkit_debug_proxy',
  proxyExeArgs: [ '--no-frontend', '--config=null:9100,:9101-9201' ],
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +0ms
  remotedebug adapter.spawnProcess, path=/usr/local/bin/ios_webkit_debug_proxy +1ms
  remotedebug adapter.spawnProcess.stderr, data=No device found, is it plugged in?
  remotedebug  +9ms
  remotedebug adapter.spawnProcess.stdout, data=Listing devices on :9100
  remotedebug  +1ms
  remotedebug adapter.spawnProcess.close, code=255 +0ms
remotedebug-ios-webkit-adapter failed to run with the following error: adapter.spawnProcess.close, code=255

**Comment by select** [comment]
@rowntreerob sorry I have the same problem, but I did not understand your answer. How did you solve it?

**Comment by lyarncheef** [comment]
verify u are running 'usbmuxd'  per the docs.... 

start your CLI with :

DEBUG=*

that should give your more detail on the issue. i cant remember exactly what solved my problem but the debug helped me zero in on where the error occur

**Comment by select** [comment]
Thanks man, I continued trying and found that I could update the iPad. This did the trick. Your hint with "not an iOS device" gave me the idea that it was probably not discovered due to some missing information that might be available in the latest iOS version. And it worked!
