### ISSUE TITLE
Does not work with VS Code?

### ISSUE THREAD

**Issue by cappi10** [RemoteDebug/remotedebug-ios-webkit-adapter#88]
When starting the debugger using the debug configuration found in the README.md file of the repository the debugger keeps loading: (please note blue loading indicator)

![screen shot 2018-02-15 at 2 34 06 pm](https://user-images.githubusercontent.com/3583974/36259285-048d672a-125e-11e8-8f31-e869d22527ef.png)

The remotedebug_ios_webkit_adapter is running and it looks like VS Code tries to connect: 

![screen shot 2018-02-15 at 2 38 48 pm](https://user-images.githubusercontent.com/3583974/36259269-fa559a98-125d-11e8-808d-3f1ee3262afa.png)

But loading continues and nothing seems to happen. VS Code does not show any warnings or errors in the developer console. 

FYI, i can get the adapter working using Chrome.

**Comment by huntercaron** [comment]
I am also having issues, but getting
```
iosAdapter.getTargets
No websocket endpoint found
``` 
over and over again.

Running with debug gets me 
```
remotedebug server.ws.onWSSConnection / +15ms
New websocket connection to /
  remotedebug adapterCollection.connectTo, url=/ +0ms
  remotedebug adapterCollection.getWebSocketId, url=/ +0ms
  remotedebug server.onWSSConnection.connectTo.error.Error: Target not found for / +0ms
  remotedebug adapterCollection.forwardTo, url=/ +5ms
  remotedebug adapterCollection.getWebSocketId, url=/ +0ms
  remotedebug adapterCollection.forwardTo, url=/ +0ms
  remotedebug adapterCollection.getWebSocketId, url=/ +0ms
  remotedebug adapterCollection.forwardTo, url=/ +0ms
  remotedebug adapterCollection.getWebSocketId, url=/ +0ms
  remotedebug adapterCollection.forwardTo, url=/ +0ms
```

works fine in chrome though

**Comment by auchenberg** [comment]
@cappi10 Does it work with Chrome DevTools for you?
