### ISSUE TITLE
Remove ios-webkit-debug-proxy as dependency

### ISSUE THREAD

**Issue by christian-bromann** [RemoteDebug/remotedebug-ios-webkit-adapter#90]
There is no need to require `ios-webkit-debug-proxy` to be installed on the system. You can simply use the `appium-remote-debugger` package to access the webkit devtools interface, e.g. when running Safari on a Simulator, you can do:

```js
import { RemoteDebugger } from 'appium-remote-debugger'

(async function() {
    const client = new RemoteDebugger({
        bundleId: 'com.apple.mobilesafari',
        platformVersion: 9
    })
    
    await client.connect()
    await client.selectApp()
    await client.selectPage(client.appIdKey.split(':')[1], 1)
    
    await client.startConsole((...args) => console.log('CONSOLE:', args))
})().then(console.log ,console.error)
```

In order to simplify the access some refactoring in the Appium package is necessary. I will work on that and propose a PR once I have something ready.

**Comment by auchenberg** [comment]
@christian-bromann Not familar with Appium. What's the scenario here?

**Comment by auchenberg** [comment]
`appium-remote-debugger` seems to be an emulation layer on top of Webkit Remote Debugging. This serves a different purpose than `ios-webkit-debug-proxy` which exploses the raw WDP connection that this adapter translates between.
