### ISSUE TITLE
There are remote targets, but how to start debugging?

### ISSUE THREAD

**Issue by yesongling** [RemoteDebug/remotedebug-ios-webkit-adapter#93]
I try to debug with this tool. By following the getting started, I saw there are two remote targets include the one I want to debug, but I do not know what to do next or how to start debugging.

**Comment by auchenberg** [comment]
What do you mean by debugging? In Chrome DevTools?

**Comment by marsjaninzmarsa** [comment]
Just open any page in Safari and click "inspect" in "Remote Target" section of page `chrome://inspect/#devices` in Chrome.

**Comment by yesongling** [comment]
Thank you all guys. I can use this debug tool by using VPN
