### ISSUE TITLE
Pretty printing/formatting of source code doesnt work in Chrome DevTools

### ISSUE THREAD

**Issue by blizzardzheng** [RemoteDebug/remotedebug-ios-webkit-adapter#94]
when i use the adapter, the chrome formatter source code feature not work.

![image](https://user-images.githubusercontent.com/11224451/40095971-3641de38-5901-11e8-8e16-450de3180eb8.png)

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
