### ISSUE TITLE
Support Chrome for iOS

### ISSUE THREAD

**Issue by denisvlr** [RemoteDebug/remotedebug-ios-webkit-adapter#95]
Is this supposed to work with Chrome for iOS?

I followed all the steps and successfully manage to inspect web pages opened through Safari as well as simple WebViews (for example links opened through the Slack iOS app), but it doesn't work when opened through Chrome for iOS. The page doesn't appear under "Remote Target".

Actually, it doesn't work either for web pages opened through the Facebook and LinkedIn iOS apps.

I also tried the Mozilla debugger.html.

My set up:
* iPhone 6S, iOS 11.3.1, Chrome for iOS 66
* Ubuntu 16.04, Chrome 66

**Comment by auchenberg** [comment]
Sadly we can't support iOS apps with custom webviews, as Apple don't allow developers to ship the apps to the app store with remote debugging enabled, so no :/

**Comment by denisvlr** [comment]
Ok thanks for your answer.

Just to clarify, how are Chrome for iOS, Facebook's or Linkedin's webviews different from the regular webviews (eg. Slack's)? I thought apps could only ship the official one.

**Comment by auchenberg** [comment]
@denisvlr I'm not expert, but there's several flavors of the web views. General rule.If you can inspect the webview via safari on MacOS, you can use this adaptor too.

**Comment by majaray** [comment]
Hi @auchenberg, are we still not able to debug Chrome on iOS?
Because as what I understand so far is that Chrome on iOS is built based on the web view, and this tool should be able to debug the web view. Am I right?
Is there any method to debug the website running on iOS Chrome?
