### ISSUE TITLE
window cannot debug the javascript?

### ISSUE THREAD

**Issue by microIBM** [RemoteDebug/remotedebug-ios-webkit-adapter#96]
window cannot debug the javascript? i cam change dom and css, but can't debug javascript.

**Comment by auchenberg** [comment]
Can you provide some more details on what JS you can't debug?

**Comment by marsjaninzmarsa** [comment]
Any? "Sources" tab just don't show JS files at all.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
