### ISSUE TITLE
mac debug ios application only records the first time into the interface

### ISSUE THREAD

**Issue by appbanana** [RemoteDebug/remotedebug-ios-webkit-adapter#97]
The environment:
iPhone6: iOS 11 
 mac version 10.13.4  
chrome version:67.0.3396.62

I debug the Safari browser on the phone normally, but debug my application only records a page that entered for the first time.How can I solve this problem?

**Comment by auchenberg** [comment]
@appbanana Please elaborate on what you mean by "record"?

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
