### ISSUE TITLE
Can't seem to debug chrome on IOS 9

### ISSUE THREAD

**Issue by markdemich** [RemoteDebug/remotedebug-ios-webkit-adapter#98]
I'm not sure if it's something I set up incorrectly, but I tried from both Mac and Windows without any luck.  Do you know if it's even possible to debug the javascript on a webpage running in Chrome on IOS 9 (it's an IPAD 2).

**Comment by duza** [comment]
Hi. I think I have a similar problem. I try to use a `remotedebug-ios-webkit-adapter` on linux (ubuntu16.04). 
I followed the instructions to install `ios-webkit-debug-proxy` and `libimobiledevice`. 
I checked connected devices (added output idevice_id and ios_webkit_debug_proxy): 
```bash
everbudding@place:~/ios-webkit-debug-proxy$ idevice_id -l
6812361931474bbf157c8c4533fabbca01a335b9
everbudding@place:~/ios-webkit-debug-proxy$ ios_webkit_debug_proxy
Listing devices on :9221
Connected :9222 to iPad (Qweeco) (6812361931474bbf157c8c4533fabbca01a335b9)
```
I think it's ok. But when I try to start remotedebug:
```bash
everbudding@place:~/ios-webkit-debug-proxy$ remotedebug_ios_webkit_adapter --port=9000
remotedebug-ios-webkit-adapter is listening on port 9000
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
iosAdapter.getTargets
...
```
I get constantly `iosAdapter.getTargets` line. In `chrome://inspect` I don't see remote devices (Chrome Version 67.0.3396.99). I try to debug Ipad Model A1490 os version 9.3.2 (13F69)

**Comment by madmicra** [comment]
I'm having a similar issue. I'm unable to debug Chrome on iOS devices but am able to debug with Chrome Dev tools when using Safari on the device. I have a Chrome iOS specific issue I need to debug and hoped this package would solve that problem. Being able to debug Safari via Chrome Dev Tools tells me it setup correctly. I've double checked it. I've tested with a 5s, 6s and an X but no luck. Is this actually designed to allow you to debug Chrome on an iOS device or just use Chrome Dev Tools to debug Safari?

**Comment by auchenberg** [comment]
Chrome on iOS can't be debugged, as it's a production app using a webview, and Apple has disabled remote debugging capabilities for this. You won't see Chrome showing up in Safari either. 

Sadly I don't know a way around this.
