### ISSUE TITLE
chrome://inspect/#devices Doesn't recognize device

### ISSUE THREAD

**Issue by mafarazuddin** [RemoteDebug/remotedebug-ios-webkit-adapter#99]
Chrome://Inspect/#devices doesn't show the device on Windows

Things did so far, 
a) Installed iTunes - Done 
b) npm install remotedebug-ios-webkit-adapter -g - Done 
c) remotedebug_ios_webkit_adapter --port=9000 - Done
d)Create a new folder named "x64" in %AppData%\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\ (sibling to "lib") and extract the ios-webkit-debug-proxy-[ver]-win64-bin.zip archive there so that the architecture detection script in iosAdapter.js will resolve to %AppData%\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\x64\ios_webkit_debug_proxy.exe  - Done

![remote debuggin](https://user-images.githubusercontent.com/18469440/41375298-766fe008-6f0a-11e8-951c-2e3186f0552b.PNG)
![chrome_inspect](https://user-images.githubusercontent.com/18469440/41375313-7f4257c4-6f0a-11e8-8c2b-55ff4cbbb412.PNG)

**Comment by jakub-g** [comment]
Which version of iOS and Windows?
Did you have "trust this device" screen displayed on iOS?

Same for me, trying to connect to iOS 12 beta device from Win 10 x64, newest iTunes from MS Store, got the "trust device" screen displayed on iOS, but Chrome doesn't see the device. Perhaps this is in line with this comment in README (though I'm on win64 so not sure)

> iOS 10 & 11 on Windows: Please be aware that iOS11 debugging might not work on Windows as the bundled version of /ios-webkit- debug-proxy-win32 may be out of date.

**Comment by mafarazuddin** [comment]
Windows 7 enterprise

iOS 10.4

iOS 10 & 11 on Windows: Please be aware that iOS11 debugging might not work on Windows as the bundled version of /ios-webkit- debug-proxy-win32 may be out of date. --> I have taken care of this my downloading 64 bit extractor and creating a foloder  as mentioned below 

Windows 64-bit environments require the following additional assets:

Download the latest Win64 release (v1.8 at time of writing)
Create a new folder named "x64" in %AppData%\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\ (sibling to "lib") and extract the ios-webkit-debug-proxy-[ver]-win64-bin.zip archive there so that the architecture detection script in iosAdapter.js will resolve to %AppData%\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\x64\ios_webkit_debug_proxy.exe properly

Any suggestions what needs to follow next?

**Comment by auchenberg** [comment]
See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79
